In [24]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import math 

dim = 4 # d_model
n = 6 # seq_length
block = 2 # block
nb = n // block # seq per block

X_src = torch.randn(n, dim)
Y_label = torch.randn(n, dim)


In [25]:

class attention(nn.Module):
    def __init__(self, dim):
        super(attention, self).__init__()
        self.dim = dim
        self.w = nn.Linear(dim, dim, bias = False)
        # self.wq = nn.Linear(dim, dim, bias = False)
        # self.wk = nn.Linear(dim, dim, bias = False)
        # self.wv = nn.Linear(dim, dim, bias = False)
        
    def forward(self, X_src):
        Y = self.w(X_src)
        # Q, K, V = self.wq(X), self.wk(X), self.wv(X)
        # S = Q @ K.t() / math.sqrt(dim)
        # # S_softmax = F.sofstmax(S, dim = 1)
        # O = S @ V
        # # Y = self.wo(O)
        return Y

model = attention(dim)
Y = model(X_src)
Y.retain_grad()

In [26]:
loss = (0.5 * (Y - Y_label) ** 2).mean() # MSE Loss
loss.backward()
# print('grad wo:', model.wo.weight.grad)
print('grad w:', model.w.weight.grad)

grad w: tensor([[ 0.0243,  0.0206,  0.0270,  0.0139],
        [-0.1795,  0.2248,  0.0520, -0.1571],
        [ 0.1021,  0.0254, -0.0604, -0.0651],
        [ 0.0133, -0.0707, -0.0044,  0.0123]])


In [34]:
print(model.w.weight.data)
print(model.w.weight.data.shape)

tensor([[ 0.4563,  0.1672, -0.3809, -0.1420],
        [-0.0038,  0.3275, -0.4761,  0.4198],
        [ 0.2018, -0.4734,  0.3049, -0.3714],
        [ 0.2734, -0.1850, -0.0005, -0.3343]])
torch.Size([4, 4])


In [35]:
print(X_src)
print(X_src.shape)

tensor([[ 2.1071, -0.8224, -0.4075,  0.9048],
        [ 0.2592,  0.6688, -0.4933, -0.5579],
        [-0.8328, -0.8627, -0.2495, -0.8758],
        [-0.5709, -0.9900,  0.5578,  0.5589],
        [ 1.2155, -1.2665, -0.3431,  1.1740],
        [ 1.7516, -1.2441, -1.1001,  0.1997]])
torch.Size([6, 4])


In [36]:
print(Y)
print(Y.shape)

tensor([[ 0.8508,  0.2965,  0.3541,  0.4259],
        [ 0.4973,  0.2187, -0.2075,  0.1339],
        [-0.3049, -0.5282,  0.4896,  0.2248],
        [-0.7179, -0.3530,  0.3160, -0.1600],
        [ 0.3070,  0.2367,  0.3041,  0.1743],
        [ 0.9821,  0.1935,  0.5327,  0.6428]], grad_fn=<MmBackward0>)
torch.Size([6, 4])


In [39]:
X_src @ model.w.weight.data.t()

tensor([[ 0.8508,  0.2965,  0.3541,  0.4259],
        [ 0.4973,  0.2187, -0.2075,  0.1339],
        [-0.3049, -0.5282,  0.4896,  0.2248],
        [-0.7179, -0.3530,  0.3160, -0.1600],
        [ 0.3070,  0.2367,  0.3041,  0.1743],
        [ 0.9821,  0.1935,  0.5327,  0.6428]])