# Gomoku MCTS Pytorch

Author xiaodongguaAIGC

五子棋 MCTS算法实现。

- agent带policy/value 网络
- 实现了state、node管理
- 实现了从零对弈
- 实现了policy/value损失
- 实现了mcts推理
- 阐述了LLM与MCTS的gap

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import math
import random
import copy

## config

In [2]:
board_size = 8
channel = 64
gomoku_number = 5  # 多少子连成一条线就算赢
exapand_size = 10
print(f'走子动作集合为:{board_size*board_size}')

走子动作集合为:64

## Gomoku Policy & Value Net Work

In [3]:
class GomokuNet(nn.Module):
    def __init__(self, board_size=15, channel=64):
        super(GomokuNet, self).__init__()
        self.board_size = board_size
        self.channel = channel
        self.conv1 = nn.Conv2d(1, 8, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(8, channel, kernel_size=3, padding=1)
        # self.conv1 = nn.Conv2d(1, channel, kernel_size=3, padding=1)
        self.fc1 = nn.Linear(channel * board_size * board_size, channel)
        self.fc2 = nn.Linear(channel, board_size * board_size)
        self.fc3 = nn.Linear(channel, 1)

    def forward(self, x):
        x1 = torch.relu(self.conv1(x))
        x2 = torch.relu(self.conv2(x1))
        x3 = x2.view(-1, self.channel * self.board_size * self.board_size)
        x4 = torch.relu(self.fc1(x3))
        policy = self.fc2(x4)
        value = torch.tanh(self.fc3(x4))
        return policy, value


model = GomokuNet(board_size=board_size, channel=channel)
# data = torch.zeros((1, 1, board_size, board_size), dtype=torch.float32)
# data = torch.randint(high = 2,size=(1, 1, board_size, board_size), dtype=torch.float32)
data = torch.randint(high=2, size=(
    1, 1, board_size, board_size), dtype=torch.float32)
policy, value = model(data)
print(policy.shape)
print(value.shape)

loss = policy[0].mean()
loss.backward()

torch.Size([1, 64])

torch.Size([1, 1])

## Mento Carlo Tree Searching

MCTS state

In [4]:
# 盘面数据
class GomokuState:
    def __init__(self, board_size=15, gomoku_number=4):
        self.board_size = board_size
        self.gomoku_number = gomoku_number

        # 盘面数据里每个格子的数据只有0(空)，1(我方)， 0(对方)
        self.board = torch.zeros(
            (1, 1, board_size, board_size), dtype=torch.float32)
        self.current_player = 1
        self.last_move = None

    def get_legal_actions(self):
        return torch.nonzero(self.board.view(-1) == 0).view(-1)
        # return torch.nonzero(self.board_int.view(-1) == 0)

    def is_terminal(self):
        # gomoku_number = 3
        if self.last_move is None:
            return False
        x, y = self.last_move
        player = self.board[0, 0, x, y]
        directions = [(1, 0), (0, 1), (1, 1), (1, -1)]
        for dx, dy in directions:
            count = 1
            for i in range(1, self.gomoku_number):
                nx, ny = x + i*dx, y + i*dy
                if 0 <= nx < self.board_size and 0 <= ny < self.board_size and self.board[0, 0, nx, ny] == player:
                    count += 1
                else:
                    break
            for i in range(1, gomoku_number):
                nx, ny = x - i*dx, y - i*dy
                if 0 <= nx < self.board_size and 0 <= ny < self.board_size and self.board[0, 0, nx, ny] == player:
                    count += 1
                else:
                    break
            if count >= self.gomoku_number:
                return True
        return len(self.get_legal_actions()) == 0

    def get_reward(self):
        if self.is_terminal():
            if self.current_player == -1:
                return 1  # Previous player (1) won
            else:
                return -1  # Previous player (-1) won
        return 0  # Game not finished

    # 对于盘面，是来回下子的，我方下子为1，对方下子为-1
    def move(self, action):
        x, y = action
        # 一定要clone，不然这里会变成in-place操作
        # 比如 t时刻 board^(t)， t时刻走子 board[0,0,x,y]=1
        # 那么在t时刻的board的数据就被替换了，将导致无法backward
        self.board = self.board.clone()
        # self.board[0, 0, x, y] = torch.tensor(self.current_player)
        # self.current_player = -torch.tensor(self.current_player)
        self.board[0, 0, x, y] = self.current_player
        self.current_player = -self.current_player
        self.last_move = action

    def clone(self):
        new_state = GomokuState(self.board_size)
        new_state.board = self.board.clone()
        new_state.current_player = self.current_player
        new_state.last_move = self.last_move
        return new_state


state = GomokuState(board_size=board_size, gomoku_number=gomoku_number)
print(f'可走子的策略为:{len(state.get_legal_actions())}')
# print(f'可走子的策略为:{state.get_legal_actions()}')

# 走子
state.move([0, 0])  # 我方
state.move([4, 0])  # 对手
state.move([0, 1])
state.move([4, 1])
print(f'是否终止:{state.is_terminal()}')
print(f'奖励:{state.get_reward()}')

state.move([0, 2])
state.move([4, 2])
state.move([0, 3])
state.move([4, 3])
state.move([0, 4])
# state.move([10,4])
print(f'是否终止:{state.is_terminal()}')
print(f'奖励:{state.get_reward()}')

可走子的策略为:64

是否终止:False

奖励:0

是否终止:True

奖励:1

In [5]:
# state = GomokuState(board_size=board_size)
print(f'可走子的策略为:{len(state.get_legal_actions())}')
print(f'可走子的策略为:{state.get_legal_actions()}')

可走子的策略为:55

可走子的策略为:tensor([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
        23, 24, 25, 26, 27, 28, 29, 30, 31, 36, 37, 38, 39, 40, 41, 42, 43, 44,
        45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62,
        63])

### MCTS Node

In [6]:
class MCTSNode:
    def __init__(self, state, parent=None):
        self.state = state
        self.parent = parent
        self.children = {}
        self.visits = 0
        self.value = 0
        self.prior = 0

    def is_fully_expanded(self):
        return len(self.children) == len(self.state.get_legal_actions())

    def is_part_expanded(self):
        return len(self.children) == 10

    def select_child(self):
        return max(self.children.items(), key=lambda x: x[1].uct_value())

    def expand(self, policy):
        # 一次拓展
        valid_actions = self.state.get_legal_actions()
        policy_mask = policy[0, valid_actions]
        max_value, max_index = torch.max(policy_mask, dim=0)
        id = valid_actions[max_index].item()
        action = [int(id/self.state.board_size),
                  int(id % self.state.board_size)]

        # action = [3,3]
        # id = 12

        child_state = self.state.clone()
        child_state.board.detach()
        child_state.move(action)
        child_node = MCTSNode(child_state, self)
        child_node.prior = policy[0, id]
        self.children[tuple(action)] = child_node
        return child_node

    def backpropagate(self, value):
        self.visits = self.visits + 1
        self.value = self.value + value
        if self.parent:
            self.parent.backpropagate(-value)

    def uct_value(self, c=1.4):
        if self.visits == 0:
            return float('inf')
        q = self.value / self.visits
        u = c * self.prior * math.sqrt(self.parent.visits) / (1 + self.visits)
        return q + u


state = GomokuState(board_size=board_size)
# 走子
state.move([0, 0])  # 我方
state.move([4, 0])  # 对手
state.move([0, 1])
state.move([4, 1])

node = MCTSNode(state)
policy, value = model(state.board)
print(policy.shape)
# policy2d = policy[0].view(board_size, board_size)
node.expand(policy)
node.backpropagate(2)
loss = (policy**2).mean()
loss.backward()
print(node.state.board)

torch.Size([1, 64])

tensor([[[[ 1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [-1., -1.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]]])

In [7]:
print(node)
print(node.children)
# print(node.children[(3,2)])

<__main__.MCTSNode object at 0x11e7fb790>

{(2, 1): <__main__.MCTSNode object at 0x10491d0d0>}

### MCTS Move

In [8]:
def mcts_move(state, net, num_simulations=1000):
    root = MCTSNode(state)
    for i in range(num_simulations):
        node = root

        while not node.state.is_terminal():
            # if not node.is_fully_expanded(): # 所有都要遍历，225？
            if not node.is_part_expanded():  # 可以限定拓展的动作空间
                policy, _ = net(node.state.board)
                policy = torch.softmax(policy, dim=1,)  # policy输出概率
                node = node.expand(policy)
                break
            else:
                node = node.select_child()[1]
        value = node.state.get_reward()
        # print(value)
        if value == 0:  # If the game is not finished, use the neural network's evaluation
            _, value = net(node.state.board)
            value = value.item()  # 估计谁能赢
            # print(value)
        # elif value == 1:
            # print(value)
            # print(value)
        node.backpropagate(value)
    return max(root.children.items(), key=lambda x: x[1].visits)[0]


a = mcts_move(state, model, num_simulations=10)
state.move(a)
final_reward = state.get_reward()
policy, _ = model(state.board)
loss = (policy**2).mean()*final_reward
loss.backward()
print(node.state.board)

tensor([[[[ 1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [-1., -1.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]]])

## MCTS Training

In [9]:
# torch.autograd.set_detect_anomaly(True)
# 初始化神经网络
net = GomokuNet(board_size=board_size, channel=channel)
optimizer = optim.Adam(net.parameters(), lr=0.001)

# 训练循环
for episode in range(100):  # 假设我们要训练1000个episode
    state = GomokuState(board_size=board_size,
                        gomoku_number=gomoku_number)  # 主流程盘面是一个
    states, policies, values = [], [], []

    # 这里下子，N
    while not state.is_terminal():
        # if True:
        policy, value = net(state.board)  # 采样策略和价值估计
        policy = torch.softmax(policy, dim=1)

        # 模拟盘数
        action = mcts_move(state, net, 100)  # mcts拓展

        states.append(state.board)
        policies.append(policy)
        values.append(value)

        state.move(action)  # 执行下棋 take action

    # 计算真实的rewards
    final_reward = state.get_reward()

    target_values = torch.tensor(
        [final_reward * ((-1) ** i) for i in range(len(values))])
    # print(target_values.shape)

    # 训练网络
    optimizer.zero_grad()
    policy_loss = -torch.mean(torch.sum(torch.stack(policies)
                              * torch.log(torch.stack(policies)), dim=1))
    value_loss = torch.mean((torch.cat(values) - target_values.detach()) ** 2)
    loss = policy_loss + value_loss

    loss.backward()
    optimizer.step()

    if episode % 1 == 0:
        print(f"Episode {episode}, Loss: {loss.item()}")
        print(loss)
        print(state.board)  # 查看盘面
        print(final_reward)

Episode 0, Loss: 1.0855109691619873

tensor(1.0855, grad_fn=<AddBackward0>)

tensor([[[[-1.,  1.,  0.,  0.,  0.,  0.,  1.,  1.],
          [ 0.,  0.,  0.,  0., -1., -1., -1.,  1.],
          [ 1.,  1., -1.,  0.,  0., -1.,  1.,  0.],
          [ 1.,  1., -1., -1.,  0.,  0.,  0., -1.],
          [ 1.,  1., -1., -1.,  0.,  1.,  0.,  0.],
          [ 0.,  0., -1.,  1.,  1., -1.,  0., -1.],
          [ 1., -1., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  0.,  0., -1.]]]])

-1

Episode 1, Loss: 1.099971055984497

tensor(1.1000, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  0.,  1., -1.,  0.,  0.,  0.,  1.],
          [ 0.,  0., -1., -1.,  0.,  0., -1.,  1.],
          [ 1., -1.,  1., -1.,  0.,  1., -1., -1.],
          [ 1.,  1.,  0., -1., -1.,  0.,  1., -1.],
          [ 1., -1.,  1.,  1.,  0., -1.,  0.,  0.],
          [ 1., -1.,  1.,  0.,  1.,  1.,  0.,  1.],
          [ 1., -1., -1., -1.,  0., -1., -1.,  0.],
          [ 0.,  0., -1., -1.,  1.,  1.,  0.,  1.]]]])

1

Episode 2, Loss: 1.0679148435592651

tensor(1.0679, grad_fn=<AddBackward0>)

tensor([[[[ 1., -1., -1., -1.,  1.,  0., -1., -1.],
          [ 1.,  0.,  1.,  1.,  1., -1.,  1., -1.],
          [ 1.,  1.,  1.,  1.,  0.,  1., -1., -1.],
          [-1.,  1.,  0., -1., -1.,  0., -1., -1.],
          [-1., -1.,  1.,  1.,  0.,  1.,  1., -1.],
          [ 1., -1.,  1., -1.,  1., -1., -1., -1.],
          [ 1.,  1., -1., -1., -1., -1.,  1., -1.],
          [ 1.,  1., -1.,  1.,  1., -1.,  1.,  1.]]]])

-1

Episode 3, Loss: 1.0722160339355469

tensor(1.0722, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  0., -1.,  1.,  0.,  0.,  0., -1.],
          [ 0.,  0.,  0., -1.,  1., -1.,  1., -1.],
          [ 0.,  1., -1.,  1.,  0., -1.,  1.,  0.],
          [ 1.,  1.,  1., -1.,  0.,  0.,  1., -1.],
          [-1.,  1.,  1.,  1.,  0.,  1.,  0.,  1.],
          [ 0.,  0.,  1.,  0., -1., -1., -1.,  1.],
          [-1., -1.,  1., -1., -1.,  1., -1., -1.],
          [ 0., -1.,  1.,  1.,  1., -1.,  0., -1.]]]])

1

Episode 4, Loss: 1.0759332180023193

tensor(1.0759, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  0., -1.,  1.,  0.,  0.,  0.,  1.],
          [ 0.,  0.,  0.,  1., -1.,  1.,  1.,  1.],
          [ 0., -1.,  1., -1.,  0., -1.,  1., -1.],
          [-1., -1., -1.,  1., -1.,  0., -1., -1.],
          [-1., -1.,  1., -1.,  0.,  1.,  0.,  0.],
          [-1.,  1.,  1.,  0., -1., -1.,  1.,  1.],
          [-1.,  1.,  1.,  1.,  1., -1., -1.,  1.],
          [ 0.,  1., -1.,  1., -1.,  1.,  0., -1.]]]])

-1

Episode 5, Loss: 1.0659178495407104

tensor(1.0659, grad_fn=<AddBackward0>)

tensor([[[[-1.,  1., -1., -1., -1.,  0.,  1.,  1.],
          [ 0.,  0., -1., -1.,  1.,  1.,  1.,  1.],
          [ 1., -1.,  1.,  1.,  0., -1.,  1., -1.],
          [-1.,  1., -1., -1.,  1.,  0., -1., -1.],
          [ 1., -1., -1., -1.,  0.,  1.,  0.,  0.],
          [-1.,  1.,  1.,  0.,  1., -1., -1.,  1.],
          [-1.,  1.,  1.,  1., -1., -1., -1., -1.],
          [-1.,  1., -1.,  1.,  1.,  1.,  1.,  1.]]]])

1

Episode 6, Loss: 1.0646600723266602

tensor(1.0647, grad_fn=<AddBackward0>)

tensor([[[[-1.,  1.,  1., -1., -1.,  0.,  1.,  1.],
          [ 0.,  0., -1., -1.,  1., -1., -1.,  1.],
          [ 1., -1.,  1.,  1.,  0.,  1., -1., -1.],
          [-1., -1., -1.,  1., -1.,  0., -1.,  1.],
          [ 1.,  1.,  1.,  1.,  0.,  1.,  0.,  0.],
          [-1.,  1.,  1.,  1., -1., -1., -1., -1.],
          [-1.,  1.,  1.,  1., -1.,  1., -1., -1.],
          [ 1.,  1.,  1., -1.,  1., -1.,  0., -1.]]]])

1

Episode 7, Loss: 1.0662859678268433

tensor(1.0663, grad_fn=<AddBackward0>)

tensor([[[[-1.,  0., -1., -1.,  0.,  0.,  0.,  1.],
          [ 0.,  0.,  1., -1.,  1.,  1., -1.,  1.],
          [ 0.,  1.,  1., -1.,  0., -1.,  1.,  0.],
          [-1., -1.,  0., -1., -1.,  0., -1.,  1.],
          [ 1.,  1.,  1., -1.,  0., -1.,  0.,  0.],
          [ 0.,  0.,  1.,  0., -1., -1.,  0.,  1.],
          [-1., -1.,  1., -1.,  1.,  1.,  1.,  0.],
          [ 0.,  0.,  1.,  0., -1.,  0.,  0.,  1.]]]])

-1

Episode 8, Loss: 1.068466067314148

tensor(1.0685, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  0.,  1.,  1.,  0.,  0.,  0., -1.],
          [ 0.,  0.,  1., -1.,  1.,  0.,  1., -1.],
          [ 0., -1.,  1.,  1.,  0.,  1.,  1.,  0.],
          [ 1., -1.,  0.,  1.,  1.,  0.,  1.,  1.],
          [-1., -1., -1.,  1.,  0., -1.,  0.,  0.],
          [ 0.,  0.,  1.,  0., -1.,  1.,  0., -1.],
          [-1., -1., -1.,  1., -1., -1.,  1.,  0.],
          [-1., -1.,  1.,  0., -1.,  0.,  0., -1.]]]])

1

Episode 9, Loss: 1.0660125017166138

tensor(1.0660, grad_fn=<AddBackward0>)

tensor([[[[-1.,  0.,  1., -1.,  0.,  0.,  0., -1.],
          [ 0.,  0., -1.,  1., -1., -1., -1., -1.],
          [ 0., -1.,  1., -1.,  0., -1., -1.,  0.],
          [-1.,  1.,  0., -1.,  1.,  0.,  1.,  1.],
          [ 1., -1.,  1.,  1.,  0.,  1.,  0.,  0.],
          [ 0., -1.,  1.,  0., -1.,  1., -1.,  1.],
          [ 1.,  1., -1.,  1.,  1.,  1.,  1.,  0.],
          [ 1., -1.,  1.,  1., -1.,  0.,  0., -1.]]]])

1

Episode 10, Loss: 1.0691825151443481

tensor(1.0692, grad_fn=<AddBackward0>)

tensor([[[[-1., -1.,  1., -1.,  0.,  0.,  0.,  1.],
          [ 0.,  0., -1., -1., -1.,  1., -1., -1.],
          [-1., -1., -1., -1.,  0.,  1., -1.,  0.],
          [ 1., -1.,  1., -1.,  0.,  0.,  1.,  1.],
          [ 1.,  1., -1., -1.,  0., -1.,  0.,  0.],
          [ 0.,  1.,  1.,  0.,  1.,  1.,  1., -1.],
          [ 1.,  1., -1.,  0.,  1.,  1.,  1., -1.],
          [ 0.,  1., -1., -1.,  1.,  0.,  0.,  1.]]]])

-1

Episode 11, Loss: 1.0659229755401611

tensor(1.0659, grad_fn=<AddBackward0>)

tensor([[[[-1.,  1., -1.,  1.,  0.,  0., -1.,  1.],
          [ 1.,  0., -1., -1., -1.,  1.,  1., -1.],
          [-1.,  1., -1., -1.,  0.,  1.,  1.,  1.],
          [ 1., -1.,  0., -1., -1.,  0.,  1., -1.],
          [ 1.,  1.,  1., -1.,  0., -1.,  0.,  0.],
          [ 1.,  1., -1., -1., -1., -1.,  1.,  1.],
          [-1.,  1.,  1., -1., -1.,  1.,  1., -1.],
          [ 1., -1., -1.,  1.,  1., -1.,  0.,  1.]]]])

-1

Episode 12, Loss: 1.066061019897461

tensor(1.0661, grad_fn=<AddBackward0>)

tensor([[[[-1.,  0., -1.,  1.,  0.,  0.,  0.,  1.],
          [ 0.,  0., -1., -1., -1., -1.,  1., -1.],
          [ 0.,  1., -1., -1.,  0.,  1.,  1.,  0.],
          [ 1., -1.,  0., -1.,  1.,  0.,  1., -1.],
          [ 1.,  1.,  1.,  1.,  0., -1.,  0.,  0.],
          [ 0.,  0., -1.,  0., -1., -1.,  0.,  1.],
          [ 1.,  1.,  1., -1., -1.,  1.,  1.,  0.],
          [ 1.,  0., -1.,  0.,  1.,  0.,  0., -1.]]]])

1

Episode 13, Loss: 1.0650781393051147

tensor(1.0651, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  0., -1.,  1.,  0.,  0.,  0.,  1.],
          [ 0.,  0.,  1., -1.,  1., -1.,  1.,  1.],
          [ 0., -1.,  1.,  0.,  0., -1., -1.,  0.],
          [ 1.,  1.,  0.,  1.,  1.,  0.,  1., -1.],
          [-1., -1., -1.,  1.,  0., -1.,  0.,  0.],
          [ 0.,  0.,  1.,  0., -1.,  1., -1., -1.],
          [ 1.,  1., -1., -1.,  1.,  1.,  1.,  0.],
          [ 1., -1., -1., -1., -1.,  0.,  0., -1.]]]])

1

Episode 14, Loss: 1.0651448965072632

tensor(1.0651, grad_fn=<AddBackward0>)

tensor([[[[-1.,  0.,  1., -1.,  0.,  0.,  0., -1.],
          [ 0.,  0., -1.,  1., -1.,  1.,  1.,  1.],
          [ 0., -1.,  1.,  0.,  0., -1., -1.,  0.],
          [-1., -1.,  0.,  1.,  0.,  0.,  1., -1.],
          [ 1., -1., -1.,  0.,  0., -1.,  0.,  0.],
          [ 0.,  0., -1.,  0.,  1.,  1.,  0.,  1.],
          [-1.,  1.,  1., -1.,  1.,  0.,  1.,  0.],
          [ 0.,  0.,  1.,  0., -1.,  0.,  0.,  1.]]]])

-1

Episode 15, Loss: 1.0651696920394897

tensor(1.0652, grad_fn=<AddBackward0>)

tensor([[[[-1., -1.,  1., -1.,  0.,  0., -1., -1.],
          [ 0.,  0.,  1., -1., -1.,  1.,  1.,  1.],
          [ 1., -1.,  1.,  1.,  0., -1., -1.,  1.],
          [-1., -1., -1.,  1., -1.,  0., -1., -1.],
          [-1.,  1., -1.,  1.,  0., -1.,  0.,  0.],
          [ 1.,  1., -1., -1.,  1.,  1.,  1.,  1.],
          [-1.,  1.,  1.,  1., -1., -1.,  1.,  1.],
          [-1.,  1.,  1., -1.,  1., -1.,  0.,  1.]]]])

-1

Episode 16, Loss: 1.0647850036621094

tensor(1.0648, grad_fn=<AddBackward0>)

tensor([[[[-1., -1.,  1., -1.,  1.,  0., -1.,  1.],
          [ 0.,  0., -1.,  1.,  1.,  1., -1., -1.],
          [ 1., -1.,  1.,  1.,  0., -1.,  1., -1.],
          [ 1.,  1.,  1., -1.,  1.,  0., -1.,  1.],
          [ 1., -1., -1.,  1.,  0.,  1.,  0.,  0.],
          [ 1., -1.,  1., -1., -1.,  1., -1.,  1.],
          [-1.,  1., -1., -1., -1.,  1., -1., -1.],
          [-1., -1., -1.,  1.,  1.,  1.,  0.,  1.]]]])

1

Episode 17, Loss: 1.0650677680969238

tensor(1.0651, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1.,  1., -1.,  0.,  0.,  1.,  1.],
          [ 0.,  0.,  1., -1.,  1., -1.,  1.,  1.],
          [-1.,  1.,  1., -1.,  0., -1., -1., -1.],
          [-1., -1., -1., -1., -1.,  0.,  1.,  1.],
          [ 1., -1., -1.,  1.,  0.,  1.,  0.,  0.],
          [ 1.,  1.,  1., -1.,  1., -1.,  1.,  1.],
          [-1., -1.,  1.,  1.,  1., -1., -1., -1.],
          [-1., -1., -1.,  1., -1.,  1.,  0., -1.]]]])

-1

Episode 18, Loss: 1.0650198459625244

tensor(1.0650, grad_fn=<AddBackward0>)

tensor([[[[ 1., -1., -1.,  1.,  0.,  0., -1., -1.],
          [ 0.,  0.,  1., -1., -1.,  1., -1., -1.],
          [-1.,  1., -1.,  1.,  0.,  1.,  1., -1.],
          [ 1., -1.,  0.,  1.,  1.,  0., -1.,  1.],
          [-1., -1.,  1., -1.,  0.,  1.,  0.,  0.],
          [ 0.,  1.,  1.,  0., -1.,  1.,  1.,  1.],
          [ 1., -1., -1.,  1., -1., -1., -1.,  1.],
          [ 1.,  1., -1., -1.,  1.,  1.,  0., -1.]]]])

1

Episode 19, Loss: 1.0653471946716309

tensor(1.0653, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1., -1.,  1.,  1.,  0.,  1., -1.],
          [ 0.,  0.,  1., -1., -1.,  1., -1., -1.],
          [ 1.,  1., -1., -1.,  1.,  1.,  1., -1.],
          [ 1., -1.,  1.,  1., -1.,  0., -1.,  1.],
          [-1., -1.,  1., -1.,  0.,  1.,  0.,  0.],
          [ 0., -1.,  1., -1., -1.,  1., -1.,  1.],
          [ 1., -1., -1.,  1.,  1., -1., -1.,  1.],
          [-1.,  1., -1., -1.,  1.,  1.,  0., -1.]]]])

1

Episode 20, Loss: 1.0657622814178467

tensor(1.0658, grad_fn=<AddBackward0>)

tensor([[[[-1.,  0.,  1.,  1.,  0.,  0.,  0., -1.],
          [ 0.,  0.,  1., -1.,  1., -1., -1.,  1.],
          [ 0., -1., -1.,  1.,  0., -1.,  1.,  0.],
          [ 1., -1.,  0.,  1.,  0.,  0.,  1.,  1.],
          [-1., -1.,  1.,  1.,  0.,  1.,  0.,  0.],
          [ 0.,  1., -1.,  0.,  1.,  1., -1.,  1.],
          [ 1.,  1., -1.,  1., -1.,  1., -1., -1.],
          [ 1., -1., -1., -1., -1., -1.,  0., -1.]]]])

-1

Episode 21, Loss: 1.0645686388015747

tensor(1.0646, grad_fn=<AddBackward0>)

tensor([[[[-1.,  1., -1., -1.,  0.,  0., -1., -1.],
          [ 0.,  0., -1.,  1.,  1.,  1., -1.,  1.],
          [ 1., -1.,  1.,  1.,  0.,  1., -1., -1.],
          [ 1., -1.,  1.,  1., -1.,  0., -1.,  1.],
          [-1.,  1.,  1., -1.,  0.,  1.,  0.,  0.],
          [ 0., -1.,  1., -1., -1.,  1.,  1.,  1.],
          [-1.,  1.,  1., -1.,  1., -1., -1.,  1.],
          [-1.,  1., -1.,  1., -1.,  1.,  0., -1.]]]])

1

Episode 22, Loss: 1.0660946369171143

tensor(1.0661, grad_fn=<AddBackward0>)

tensor([[[[-1.,  1.,  1.,  1.,  0.,  0.,  1., -1.],
          [ 0.,  0.,  1., -1., -1.,  1., -1., -1.],
          [-1.,  1.,  1., -1.,  0., -1.,  1.,  0.],
          [-1.,  1.,  0.,  1., -1.,  0., -1., -1.],
          [-1., -1.,  1.,  1.,  0., -1.,  0.,  0.],
          [ 0.,  1.,  1.,  0., -1.,  1., -1.,  1.],
          [-1., -1.,  1.,  1.,  1., -1.,  1., -1.],
          [ 1.,  1.,  1., -1., -1.,  1.,  0., -1.]]]])

-1

Episode 23, Loss: 1.0645430088043213

tensor(1.0645, grad_fn=<AddBackward0>)

tensor([[[[-1.,  0., -1., -1.,  0.,  0.,  0., -1.],
          [ 0.,  0., -1.,  1., -1.,  1., -1., -1.],
          [ 0., -1.,  1.,  0.,  0., -1.,  1.,  0.],
          [-1.,  1.,  0.,  1.,  0.,  0., -1., -1.],
          [-1.,  1.,  1.,  1.,  0., -1.,  0.,  0.],
          [ 0., -1.,  1.,  0., -1.,  1.,  1.,  1.],
          [ 1.,  1.,  1., -1., -1.,  1.,  1., -1.],
          [-1.,  1.,  1.,  1.,  1.,  1.,  0., -1.]]]])

1

Episode 24, Loss: 1.0648654699325562

tensor(1.0649, grad_fn=<AddBackward0>)

tensor([[[[-1.,  0., -1., -1.,  0.,  0.,  0., -1.],
          [ 0.,  0., -1.,  1.,  1.,  1.,  1.,  1.],
          [ 0.,  1.,  1.,  0.,  0., -1., -1.,  0.],
          [-1., -1.,  0.,  1.,  0.,  0., -1., -1.],
          [-1.,  1., -1.,  0.,  0., -1.,  0.,  0.],
          [ 0.,  0., -1.,  0.,  1.,  1.,  0.,  1.],
          [-1.,  1.,  1., -1.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  1.,  0.,  0.,  1.]]]])

1

Episode 25, Loss: 1.0650568008422852

tensor(1.0651, grad_fn=<AddBackward0>)

tensor([[[[ 1., -1., -1., -1.,  0.,  0.,  1., -1.],
          [-1.,  0., -1.,  1., -1.,  1.,  1.,  1.],
          [ 1., -1.,  1., -1., -1., -1., -1., -1.],
          [-1., -1.,  1.,  1.,  1.,  0.,  1., -1.],
          [-1.,  1., -1.,  1.,  0., -1.,  0.,  0.],
          [ 1.,  1., -1., -1.,  1.,  1., -1.,  1.],
          [-1.,  1.,  1.,  1.,  1., -1.,  1., -1.],
          [-1., -1.,  1.,  1., -1.,  1.,  0.,  1.]]]])

-1

Episode 26, Loss: 1.065415620803833

tensor(1.0654, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  0.,  1.,  1.,  0.,  0.,  0., -1.],
          [ 0.,  0.,  1., -1., -1.,  1.,  1.,  1.],
          [ 0., -1., -1.,  0.,  0.,  1., -1.,  0.],
          [-1.,  1.,  0.,  1.,  0.,  0.,  1., -1.],
          [-1., -1., -1., -1.,  0., -1.,  0.,  0.],
          [ 0., -1.,  1.,  0., -1.,  1., -1.,  1.],
          [ 1., -1., -1.,  0., -1.,  0.,  1.,  0.],
          [ 1.,  1.,  1.,  1.,  1.,  0.,  0., -1.]]]])

1

Episode 27, Loss: 1.0688941478729248

tensor(1.0689, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  0., -1., -1.,  0.,  0.,  0., -1.],
          [ 0.,  0., -1.,  1., -1.,  1.,  1.,  1.],
          [ 0., -1.,  1.,  1.,  0., -1.,  1.,  0.],
          [-1., -1.,  0.,  1., -1.,  0.,  1., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  0.,  0.],
          [ 0., -1., -1.,  0., -1., -1.,  0.,  1.],
          [ 1.,  1.,  1.,  1.,  1., -1.,  1.,  0.],
          [-1.,  0.,  1.,  0.,  1.,  0.,  0.,  1.]]]])

1

Episode 28, Loss: 1.0650168657302856

tensor(1.0650, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1.,  1., -1.,  0.,  0., -1., -1.],
          [ 0.,  0., -1.,  1.,  1., -1.,  1., -1.],
          [ 1.,  1.,  1., -1.,  0.,  1.,  1., -1.],
          [-1.,  1.,  0.,  1.,  1.,  0.,  1., -1.],
          [-1.,  1., -1., -1.,  0., -1.,  0.,  0.],
          [ 0., -1., -1., -1., -1., -1.,  1.,  1.],
          [-1., -1.,  1., -1.,  1., -1.,  1.,  1.],
          [ 1.,  1.,  1.,  1., -1., -1.,  0., -1.]]]])

-1

Episode 29, Loss: 1.065361499786377

tensor(1.0654, grad_fn=<AddBackward0>)

tensor([[[[-1.,  1., -1., -1., -1., -1., -1., -1.],
          [ 1.,  0., -1.,  1.,  1., -1.,  1.,  1.],
          [ 1.,  1.,  1., -1., -1.,  1., -1., -1.],
          [-1.,  1.,  1.,  1., -1.,  0.,  1., -1.],
          [-1.,  1., -1., -1.,  0., -1.,  0.,  0.],
          [ 1., -1.,  1.,  1., -1., -1.,  1.,  1.],
          [-1., -1.,  1., -1., -1.,  1.,  1., -1.],
          [ 1.,  1.,  1.,  1., -1.,  1.,  0.,  1.]]]])

-1

Episode 30, Loss: 1.0668083429336548

tensor(1.0668, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1.,  1., -1.,  1.,  1.,  1., -1.],
          [-1.,  1., -1.,  1.,  1., -1.,  1.,  1.],
          [ 1., -1., -1., -1.,  1., -1., -1., -1.],
          [-1.,  1.,  1., -1.,  1., -1., -1., -1.],
          [ 1., -1., -1., -1., -1.,  1., -1., -1.],
          [-1.,  1.,  1., -1., -1., -1.,  1.,  1.],
          [-1.,  1.,  1.,  1., -1.,  1.,  1., -1.],
          [ 1., -1.,  1.,  1., -1.,  1., -1.,  1.]]]])

-1

Episode 31, Loss: 1.0670047998428345

tensor(1.0670, grad_fn=<AddBackward0>)

tensor([[[[-1.,  1., -1.,  1.,  0.,  0.,  1., -1.],
          [-1.,  0., -1.,  1., -1.,  1.,  1.,  1.],
          [ 1.,  1.,  1., -1.,  0., -1., -1., -1.],
          [-1.,  1.,  0., -1.,  1.,  0.,  1., -1.],
          [-1., -1., -1., -1.,  0.,  1.,  0.,  0.],
          [-1., -1.,  1., -1., -1., -1.,  1.,  1.],
          [-1.,  1.,  1., -1., -1.,  1.,  1.,  1.],
          [ 1., -1.,  1.,  1.,  1., -1.,  0.,  1.]]]])

-1

Episode 32, Loss: 1.0648579597473145

tensor(1.0649, grad_fn=<AddBackward0>)

tensor([[[[ 1., -1.,  1., -1.,  0.,  0.,  0.,  1.],
          [ 0.,  0., -1.,  1.,  1., -1.,  1., -1.],
          [-1.,  1., -1., -1.,  0.,  1.,  1.,  1.],
          [-1., -1., -1., -1., -1.,  0.,  1., -1.],
          [-1.,  1.,  1., -1.,  0.,  1.,  0.,  0.],
          [ 0.,  1., -1.,  1., -1., -1.,  1., -1.],
          [-1., -1.,  1.,  1., -1., -1.,  1.,  1.],
          [ 1.,  1.,  1.,  1., -1., -1.,  0.,  1.]]]])

-1

Episode 33, Loss: 1.0645262002944946

tensor(1.0645, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1.,  1., -1.,  0.,  0., -1.,  1.],
          [ 0.,  0., -1.,  1.,  1., -1.,  1., -1.],
          [ 1.,  1.,  1.,  1.,  1., -1., -1., -1.],
          [ 1., -1.,  1.,  1., -1.,  0., -1., -1.],
          [-1.,  1., -1., -1.,  0., -1.,  0.,  0.],
          [ 0.,  1., -1.,  0., -1.,  1.,  1.,  1.],
          [-1.,  1.,  1.,  1.,  1., -1.,  1., -1.],
          [ 1., -1., -1., -1.,  1., -1.,  0., -1.]]]])

1

Episode 34, Loss: 1.0645335912704468

tensor(1.0645, grad_fn=<AddBackward0>)

tensor([[[[-1.,  0., -1., -1.,  0.,  0.,  0.,  1.],
          [ 0.,  0., -1.,  1.,  1., -1.,  1.,  1.],
          [ 0.,  1., -1.,  0.,  0.,  1.,  1.,  0.],
          [-1.,  1.,  0.,  1.,  0.,  0.,  1., -1.],
          [-1.,  1.,  1.,  0.,  0., -1.,  0.,  0.],
          [ 0.,  1., -1.,  0., -1.,  1.,  0.,  1.],
          [-1.,  1., -1., -1.,  1.,  1.,  1.,  0.],
          [ 0., -1., -1., -1.,  0.,  0.,  0., -1.]]]])

1

Episode 35, Loss: 1.0646065473556519

tensor(1.0646, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1.,  1., -1., -1.,  1., -1., -1.],
          [-1., -1., -1.,  1., -1.,  1.,  1., -1.],
          [ 1.,  1., -1., -1.,  1.,  1., -1.,  1.],
          [ 1., -1., -1., -1., -1.,  1., -1.,  1.],
          [-1.,  1.,  1.,  1.,  0.,  1., -1.,  1.],
          [ 1.,  1., -1.,  1., -1., -1., -1., -1.],
          [ 1.,  1., -1.,  1.,  1., -1.,  1., -1.],
          [-1.,  1.,  1.,  1., -1., -1.,  1., -1.]]]])

1

Episode 36, Loss: 1.064980149269104

tensor(1.0650, grad_fn=<AddBackward0>)

tensor([[[[ 1., -1.,  1.,  1.,  0.,  0.,  0., -1.],
          [ 0.,  0., -1.,  1., -1.,  1.,  1.,  1.],
          [ 0., -1., -1., -1.,  0., -1.,  1.,  0.],
          [ 1., -1.,  0., -1., -1.,  0., -1.,  1.],
          [-1.,  1., -1., -1.,  0.,  1.,  0.,  0.],
          [ 0.,  1., -1.,  0., -1.,  1.,  1., -1.],
          [-1., -1., -1.,  1., -1.,  1.,  1.,  1.],
          [-1., -1.,  1.,  1.,  1.,  1.,  0.,  1.]]]])

-1

Episode 37, Loss: 1.0647896528244019

tensor(1.0648, grad_fn=<AddBackward0>)

tensor([[[[ 1., -1., -1., -1.,  0., -1., -1.,  1.],
          [-1.,  0., -1.,  1., -1.,  1., -1.,  1.],
          [ 1.,  1., -1.,  1., -1., -1.,  1.,  1.],
          [-1.,  1.,  1., -1.,  1.,  0., -1.,  1.],
          [-1.,  1., -1.,  1.,  0.,  1., -1., -1.],
          [ 1., -1.,  1.,  1., -1.,  1., -1., -1.],
          [ 1., -1.,  1., -1.,  1.,  1.,  1.,  1.],
          [-1.,  1., -1., -1.,  1., -1.,  1., -1.]]]])

-1

Episode 38, Loss: 1.0666688680648804

tensor(1.0667, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1.,  1., -1.,  0.,  0.,  0.,  1.],
          [ 0.,  0., -1.,  1., -1.,  1., -1., -1.],
          [ 1.,  1.,  1., -1.,  0.,  1., -1.,  0.],
          [ 1., -1., -1., -1.,  0.,  0., -1.,  1.],
          [-1.,  1., -1.,  1.,  0.,  1.,  0.,  0.],
          [ 0., -1., -1.,  0., -1.,  1., -1., -1.],
          [ 1.,  1., -1.,  1.,  1.,  1.,  1.,  0.],
          [-1., -1., -1.,  1., -1.,  1.,  0., -1.]]]])

-1

Episode 39, Loss: 1.064496397972107

tensor(1.0645, grad_fn=<AddBackward0>)

tensor([[[[-1.,  0., -1., -1.,  0.,  0.,  0.,  1.],
          [ 0.,  0., -1.,  1.,  1., -1.,  1., -1.],
          [ 0.,  1., -1.,  0.,  0., -1.,  1.,  0.],
          [-1., -1.,  0., -1.,  0.,  0.,  0.,  1.],
          [-1.,  1.,  1.,  0.,  0.,  1.,  0.,  0.],
          [ 0.,  0.,  1.,  0.,  1., -1.,  0., -1.],
          [ 1.,  1.,  1.,  1.,  1., -1.,  1.,  0.],
          [ 0.,  0., -1.,  0.,  0.,  0.,  0., -1.]]]])

1

Episode 40, Loss: 1.0668805837631226

tensor(1.0669, grad_fn=<AddBackward0>)

tensor([[[[-1.,  1.,  1.,  1.,  0.,  1.,  0., -1.],
          [ 0.,  0.,  1.,  1., -1., -1.,  1., -1.],
          [ 1.,  1., -1., -1.,  0.,  1.,  1., -1.],
          [-1., -1.,  1., -1., -1.,  0.,  1.,  1.],
          [-1., -1.,  1., -1.,  0., -1.,  0.,  0.],
          [ 0.,  1.,  1.,  0.,  1.,  1., -1.,  1.],
          [-1., -1.,  1.,  1., -1.,  1.,  1., -1.],
          [-1.,  1., -1., -1.,  1., -1.,  0., -1.]]]])

-1

Episode 41, Loss: 1.0643223524093628

tensor(1.0643, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1., -1., -1.,  0.,  0.,  0., -1.],
          [ 0.,  0., -1.,  1.,  1.,  1., -1., -1.],
          [-1.,  1., -1.,  1.,  0., -1.,  1.,  0.],
          [-1.,  1.,  0., -1.,  1.,  0., -1., -1.],
          [-1.,  1.,  1., -1.,  0.,  1.,  0.,  0.],
          [ 0., -1.,  1.,  0.,  1.,  1.,  1.,  1.],
          [-1., -1.,  1., -1.,  1., -1.,  1.,  1.],
          [-1., -1., -1.,  1., -1.,  1.,  0.,  1.]]]])

1

Episode 42, Loss: 1.0664843320846558

tensor(1.0665, grad_fn=<AddBackward0>)

tensor([[[[-1., -1.,  1., -1.,  0.,  1.,  0.,  1.],
          [ 0.,  0., -1.,  1., -1.,  1., -1., -1.],
          [-1.,  1.,  1.,  1., -1.,  1.,  1.,  1.],
          [ 1., -1.,  1., -1., -1.,  0., -1., -1.],
          [-1.,  1.,  1., -1.,  0., -1.,  0.,  0.],
          [ 0.,  1.,  1., -1., -1.,  1.,  1.,  1.],
          [-1., -1., -1., -1.,  1.,  1.,  1., -1.],
          [ 1., -1.,  1., -1.,  1.,  1.,  0., -1.]]]])

-1

Episode 43, Loss: 1.0662543773651123

tensor(1.0663, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1.,  1., -1.,  0., -1.,  0.,  1.],
          [ 0.,  0.,  1.,  1., -1., -1., -1., -1.],
          [-1.,  1., -1.,  1.,  1.,  1., -1., -1.],
          [-1., -1.,  1., -1.,  1.,  0.,  1., -1.],
          [-1.,  1.,  1., -1.,  0., -1.,  0.,  0.],
          [ 0.,  1., -1., -1.,  1., -1.,  1.,  1.],
          [ 1.,  1.,  1., -1.,  1.,  1.,  1.,  1.],
          [-1., -1.,  1., -1., -1., -1.,  0., -1.]]]])

-1

Episode 44, Loss: 1.0655839443206787

tensor(1.0656, grad_fn=<AddBackward0>)

tensor([[[[ 1., -1.,  1., -1.,  0.,  0.,  0., -1.],
          [ 0.,  0., -1.,  1., -1., -1.,  1., -1.],
          [ 0., -1., -1.,  1.,  0., -1.,  1., -1.],
          [ 1., -1.,  0., -1.,  1.,  0., -1., -1.],
          [ 1., -1., -1.,  1.,  0.,  1.,  0.,  0.],
          [ 0., -1., -1.,  0.,  1.,  1.,  1., -1.],
          [ 1.,  1., -1.,  1., -1.,  1.,  1.,  1.],
          [ 1., -1.,  1., -1.,  1.,  1.,  0.,  1.]]]])

1

Episode 45, Loss: 1.064485788345337

tensor(1.0645, grad_fn=<AddBackward0>)

tensor([[[[-1.,  0., -1.,  1.,  0.,  0.,  0., -1.],
          [ 0.,  0., -1.,  1.,  1.,  1.,  1.,  1.],
          [ 0., -1.,  1.,  0.,  0., -1., -1.,  0.],
          [ 1.,  1.,  0., -1.,  0.,  0.,  0., -1.],
          [ 1., -1.,  1.,  0.,  0.,  1.,  0.,  0.],
          [ 0.,  0.,  1.,  0.,  1., -1.,  0., -1.],
          [-1.,  1., -1.,  0.,  0., -1.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  0.,  0., -1.]]]])

1

Episode 46, Loss: 1.0648362636566162

tensor(1.0648, grad_fn=<AddBackward0>)

tensor([[[[-1.,  0.,  1.,  1.,  0.,  0.,  0.,  1.],
          [ 0.,  0., -1.,  1., -1.,  1., -1.,  1.],
          [ 0., -1., -1., -1.,  0., -1., -1.,  0.],
          [ 1., -1.,  0., -1.,  0.,  0.,  1., -1.],
          [ 1., -1., -1.,  0.,  0.,  1.,  0.,  0.],
          [ 0.,  1.,  1.,  0.,  1.,  1., -1., -1.],
          [ 1.,  1., -1.,  1., -1.,  1.,  1.,  0.],
          [-1.,  1.,  1.,  0.,  0.,  0.,  0., -1.]]]])

1

Episode 47, Loss: 1.0644004344940186

tensor(1.0644, grad_fn=<AddBackward0>)

tensor([[[[-1., -1.,  1., -1.,  0.,  0.,  0., -1.],
          [ 0.,  0., -1.,  1.,  1., -1.,  1.,  1.],
          [ 0., -1.,  1., -1.,  1., -1.,  1.,  0.],
          [ 1., -1.,  0., -1., -1.,  0., -1., -1.],
          [-1.,  1.,  1.,  0.,  0., -1.,  0.,  0.],
          [ 0., -1., -1.,  0., -1., -1.,  1.,  1.],
          [ 1., -1.,  1., -1.,  1.,  1.,  1.,  0.],
          [ 1., -1.,  1.,  1.,  0.,  1.,  0.,  1.]]]])

-1

Episode 48, Loss: 1.064195990562439

tensor(1.0642, grad_fn=<AddBackward0>)

tensor([[[[ 1., -1.,  1.,  1.,  0.,  1.,  0., -1.],
          [ 0.,  0.,  1.,  1.,  1., -1.,  1.,  1.],
          [ 1., -1.,  1.,  1.,  1., -1.,  1., -1.],
          [ 1., -1.,  0., -1.,  1.,  0., -1., -1.],
          [ 1., -1., -1., -1.,  0., -1.,  0.,  0.],
          [ 0.,  1., -1.,  1., -1., -1.,  1.,  1.],
          [-1., -1.,  1., -1., -1., -1.,  1.,  0.],
          [-1., -1.,  1., -1., -1.,  1.,  0.,  1.]]]])

-1

Episode 49, Loss: 1.0642695426940918

tensor(1.0643, grad_fn=<AddBackward0>)

tensor([[[[-1., -1.,  1.,  1.,  0., -1.,  0., -1.],
          [ 0.,  0.,  1.,  1.,  1.,  1., -1., -1.],
          [ 1., -1.,  1.,  1., -1.,  1.,  1., -1.],
          [-1.,  1.,  0., -1., -1.,  0.,  1., -1.],
          [-1.,  1., -1., -1.,  0.,  1.,  0., -1.],
          [ 0.,  1., -1.,  1., -1., -1., -1.,  1.],
          [-1.,  1.,  1., -1., -1., -1.,  1.,  1.],
          [-1., -1.,  1.,  1.,  1.,  1.,  0.,  1.]]]])

-1

Episode 50, Loss: 1.0642493963241577

tensor(1.0642, grad_fn=<AddBackward0>)

tensor([[[[-1.,  0., -1.,  1.,  0.,  0.,  0., -1.],
          [ 0.,  0.,  1.,  1.,  1.,  0., -1.,  1.],
          [ 0., -1.,  1.,  0.,  0.,  1.,  1.,  0.],
          [-1.,  1.,  0., -1.,  0.,  0.,  0.,  1.],
          [-1.,  1.,  1.,  0.,  0., -1.,  0.,  0.],
          [ 0.,  0.,  1.,  0., -1.,  1.,  0.,  1.],
          [-1., -1., -1., -1., -1., -1.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  0.,  0., -1.]]]])

-1

Episode 51, Loss: 1.0639303922653198

tensor(1.0639, grad_fn=<AddBackward0>)

tensor([[[[-1.,  1.,  1.,  1.,  0., -1.,  0.,  1.],
          [ 0.,  0., -1.,  1.,  1.,  1., -1.,  1.],
          [-1., -1., -1.,  1., -1., -1., -1.,  0.],
          [-1.,  1.,  1., -1.,  0.,  0.,  0.,  1.],
          [ 1., -1.,  1.,  0.,  0.,  1.,  0., -1.],
          [ 0., -1., -1.,  1., -1., -1., -1.,  1.],
          [-1.,  1., -1., -1.,  1., -1.,  1.,  0.],
          [ 1., -1.,  1.,  1.,  0.,  1.,  0.,  1.]]]])

1

Episode 52, Loss: 1.063844084739685

tensor(1.0638, grad_fn=<AddBackward0>)

tensor([[[[ 1., -1., -1., -1.,  1., -1., -1., -1.],
          [-1.,  1.,  1.,  1., -1.,  1., -1., -1.],
          [-1., -1.,  1.,  1.,  1., -1.,  1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  1.],
          [ 1., -1., -1.,  1., -1.,  1., -1.,  1.],
          [-1., -1., -1.,  1., -1.,  1., -1., -1.],
          [ 1.,  1.,  1.,  1., -1., -1.,  1.,  1.],
          [ 1., -1.,  1., -1., -1.,  1.,  1.,  1.]]]])

-1

Episode 53, Loss: 1.06437349319458

tensor(1.0644, grad_fn=<AddBackward0>)

tensor([[[[-1., -1., -1.,  1.,  0., -1.,  0., -1.],
          [ 0.,  0.,  1.,  1.,  1., -1., -1., -1.],
          [ 1., -1.,  1., -1.,  1.,  1., -1.,  0.],
          [ 1.,  1.,  1., -1., -1.,  0.,  0.,  1.],
          [ 1., -1.,  1.,  0.,  0.,  1.,  0., -1.],
          [ 0., -1., -1., -1., -1., -1.,  1., -1.],
          [-1.,  1.,  1., -1.,  1., -1.,  1.,  0.],
          [ 1., -1.,  1.,  1.,  0.,  1.,  0.,  1.]]]])

-1

Episode 54, Loss: 1.0639234781265259

tensor(1.0639, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1.,  1., -1.,  0., -1.,  0., -1.],
          [ 0.,  0., -1.,  1.,  1., -1., -1., -1.],
          [ 0., -1.,  1.,  1., -1.,  1.,  1.,  0.],
          [ 1., -1.,  0., -1.,  0.,  0.,  0., -1.],
          [ 1., -1., -1.,  0.,  0.,  1.,  0.,  0.],
          [ 0., -1., -1.,  0., -1., -1.,  1.,  1.],
          [ 1., -1.,  1.,  1., -1., -1.,  1.,  0.],
          [ 1., -1.,  1.,  0.,  0.,  1.,  0.,  1.]]]])

-1

Episode 55, Loss: 1.0637460947036743

tensor(1.0637, grad_fn=<AddBackward0>)

tensor([[[[-1., -1., -1., -1.,  0.,  1.,  0.,  1.],
          [-1., -1., -1.,  1.,  1., -1., -1., -1.],
          [ 1., -1.,  1.,  1.,  1.,  1., -1.,  1.],
          [ 1.,  1.,  1., -1., -1.,  0.,  1., -1.],
          [ 1., -1., -1., -1.,  0.,  1.,  1., -1.],
          [ 1.,  1., -1., -1., -1., -1.,  1.,  1.],
          [ 1.,  1.,  1.,  1., -1., -1.,  1.,  1.],
          [-1., -1.,  1.,  1., -1., -1.,  0.,  1.]]]])

1

Episode 56, Loss: 1.0635191202163696

tensor(1.0635, grad_fn=<AddBackward0>)

tensor([[[[-1.,  1., -1., -1.,  0., -1.,  0., -1.],
          [ 0.,  0.,  1.,  1.,  1.,  1., -1.,  1.],
          [ 1., -1.,  1., -1., -1.,  1.,  1.,  0.],
          [ 1., -1., -1., -1., -1.,  0.,  1., -1.],
          [ 1., -1.,  1.,  0.,  0., -1.,  0.,  1.],
          [ 0.,  1.,  1.,  1.,  1.,  1., -1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [-1., -1.,  1., -1.,  0.,  1.,  0., -1.]]]])

1

Episode 57, Loss: 1.064457654953003

tensor(1.0645, grad_fn=<AddBackward0>)

tensor([[[[-1.,  1., -1., -1.,  0., -1.,  0.,  1.],
          [ 0.,  0.,  1.,  1., -1.,  1., -1., -1.],
          [ 0.,  1.,  1.,  1., -1.,  1.,  1.,  0.],
          [ 1., -1.,  0., -1., -1.,  0.,  1., -1.],
          [-1., -1., -1.,  0.,  0.,  1.,  0.,  0.],
          [ 0.,  1., -1.,  0.,  1.,  1., -1.,  1.],
          [ 1., -1., -1.,  1., -1., -1.,  1.,  0.],
          [ 1., -1.,  1., -1.,  0.,  1.,  0.,  1.]]]])

1

Episode 58, Loss: 1.0634219646453857

tensor(1.0634, grad_fn=<AddBackward0>)

tensor([[[[ 1., -1., -1., -1.,  0., -1.,  0.,  1.],
          [ 1.,  0., -1.,  1., -1., -1., -1.,  1.],
          [-1.,  1., -1., -1.,  1.,  1.,  1.,  0.],
          [ 1.,  1., -1., -1.,  1.,  0., -1., -1.],
          [-1., -1., -1.,  0.,  0., -1.,  0., -1.],
          [ 0., -1., -1.,  1.,  1., -1.,  1.,  1.],
          [ 1., -1., -1.,  1.,  1., -1.,  1.,  0.],
          [ 1.,  1.,  1.,  1.,  0.,  1.,  0.,  1.]]]])

-1

Episode 59, Loss: 1.063483715057373

tensor(1.0635, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1., -1.,  1.,  0., -1.,  0., -1.],
          [ 0.,  0., -1.,  1.,  1.,  1., -1.,  1.],
          [-1.,  1., -1., -1., -1.,  1.,  1.,  0.],
          [ 1.,  1., -1., -1., -1.,  0.,  0., -1.],
          [-1., -1., -1.,  0.,  0., -1.,  0., -1.],
          [ 0.,  1., -1.,  1.,  1., -1.,  1.,  1.],
          [ 1., -1.,  1.,  1., -1., -1.,  1.,  0.],
          [ 1., -1., -1.,  1.,  0.,  1.,  0.,  1.]]]])

-1

Episode 60, Loss: 1.063455581665039

tensor(1.0635, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1.,  1., -1.,  0.,  1.,  0.,  1.],
          [-1.,  0.,  1.,  1.,  1., -1., -1., -1.],
          [-1.,  1.,  1., -1., -1., -1.,  1.,  0.],
          [ 1., -1.,  0., -1.,  1.,  0.,  1., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  1.,  1.],
          [ 0., -1.,  1.,  0.,  1.,  1.,  1., -1.],
          [-1.,  1.,  1.,  1., -1., -1.,  1.,  0.],
          [-1., -1., -1.,  1.,  0., -1.,  0., -1.]]]])

1

Episode 61, Loss: 1.0631048679351807

tensor(1.0631, grad_fn=<AddBackward0>)

tensor([[[[ 1., -1.,  1., -1.,  0.,  1.,  0.,  1.],
          [ 0.,  0., -1.,  1.,  1., -1., -1., -1.],
          [ 1.,  1.,  1.,  1.,  1., -1., -1.,  0.],
          [ 1., -1.,  0.,  1., -1.,  0.,  0., -1.],
          [-1., -1.,  1.,  0.,  0.,  1.,  0.,  1.],
          [ 0.,  1.,  1.,  0.,  1.,  1., -1., -1.],
          [-1.,  1., -1., -1.,  1., -1.,  1.,  0.],
          [-1.,  1., -1.,  0.,  0., -1.,  0., -1.]]]])

1

Episode 62, Loss: 1.0630625486373901

tensor(1.0631, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1.,  1., -1.,  0., -1.,  0., -1.],
          [-1.,  1., -1.,  1., -1.,  1., -1.,  1.],
          [-1.,  1.,  1.,  1.,  1., -1., -1.,  0.],
          [ 1., -1.,  1.,  1.,  1.,  0., -1., -1.],
          [-1., -1., -1.,  1.,  0., -1.,  1.,  1.],
          [ 0., -1.,  1., -1.,  1.,  1., -1., -1.],
          [ 1.,  1., -1.,  1.,  1., -1.,  1.,  0.],
          [ 1., -1., -1., -1.,  0., -1.,  0.,  1.]]]])

1

Episode 63, Loss: 1.062806487083435

tensor(1.0628, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1.,  1., -1.,  0.,  1.,  0., -1.],
          [ 0.,  0.,  1.,  1., -1., -1., -1.,  1.],
          [ 1.,  1.,  1.,  1.,  1., -1., -1.,  0.],
          [ 1., -1.,  0.,  1.,  1.,  0.,  0., -1.],
          [-1., -1., -1.,  0.,  0., -1.,  0., -1.],
          [ 0., -1.,  1.,  0.,  1.,  1., -1., -1.],
          [ 1.,  1., -1.,  1.,  1., -1.,  1.,  0.],
          [-1., -1., -1.,  0.,  0., -1.,  0.,  1.]]]])

1

Episode 64, Loss: 1.0625184774398804

tensor(1.0625, grad_fn=<AddBackward0>)

tensor([[[[ 1., -1., -1., -1.,  0., -1.,  0., -1.],
          [ 0.,  0.,  1.,  1., -1.,  1., -1.,  1.],
          [ 1.,  1.,  1.,  1.,  1., -1., -1.,  0.],
          [ 1., -1.,  0.,  1., -1.,  0.,  0.,  1.],
          [ 1., -1., -1.,  0.,  0., -1.,  0., -1.],
          [ 0.,  1., -1.,  0.,  1.,  1., -1., -1.],
          [ 1.,  1., -1.,  1.,  1., -1.,  1.,  0.],
          [-1., -1., -1.,  0.,  0.,  1.,  0.,  1.]]]])

1

Episode 65, Loss: 1.061705231666565

tensor(1.0617, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1., -1.,  1.,  0., -1.,  0.,  1.],
          [-1.,  1.,  1.,  1., -1., -1., -1., -1.],
          [ 1.,  1.,  1.,  1., -1., -1., -1., -1.],
          [ 1., -1.,  1.,  1.,  1.,  0., -1.,  1.],
          [-1., -1., -1.,  1.,  0., -1.,  1., -1.],
          [ 0., -1.,  1., -1.,  1., -1.,  1.,  1.],
          [ 1.,  1., -1., -1.,  1., -1.,  1.,  0.],
          [-1.,  1., -1., -1.,  1.,  1.,  0., -1.]]]])

1

Episode 66, Loss: 1.0617443323135376

tensor(1.0617, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1., -1.,  1.,  0., -1.,  0.,  1.],
          [-1.,  1., -1.,  1.,  1., -1., -1., -1.],
          [ 1.,  1.,  1., -1., -1., -1., -1., -1.],
          [ 1., -1.,  1.,  1.,  1.,  1., -1.,  1.],
          [-1., -1., -1.,  1.,  0., -1., -1., -1.],
          [ 0.,  1.,  1.,  1.,  1., -1.,  1.,  1.],
          [ 1.,  1., -1., -1.,  1., -1.,  1.,  0.],
          [-1.,  1., -1., -1., -1.,  1.,  0., -1.]]]])

-1

Episode 67, Loss: 1.0614665746688843

tensor(1.0615, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1., -1.,  1.,  0., -1.,  0., -1.],
          [-1.,  1., -1.,  1.,  1., -1., -1., -1.],
          [ 1.,  1.,  1., -1., -1., -1., -1., -1.],
          [ 1., -1.,  1.,  1.,  1.,  1., -1.,  1.],
          [ 1., -1., -1.,  0.,  0., -1., -1., -1.],
          [ 0.,  1.,  1.,  1.,  1., -1.,  1.,  1.],
          [ 1.,  1., -1., -1.,  1., -1.,  1.,  0.],
          [-1.,  1., -1., -1.,  0.,  1.,  0., -1.]]]])

-1

Episode 68, Loss: 1.0609170198440552

tensor(1.0609, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1., -1., -1.,  0., -1.,  0., -1.],
          [ 0.,  0., -1.,  1.,  1., -1.,  1.,  1.],
          [ 1.,  1.,  1.,  1.,  1., -1., -1.,  0.],
          [ 1., -1.,  0.,  1.,  1.,  0.,  0.,  1.],
          [ 1., -1., -1.,  0.,  0., -1.,  0., -1.],
          [ 0., -1., -1.,  0.,  1., -1., -1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [ 1.,  1., -1.,  0.,  0., -1.,  0.,  1.]]]])

1

Episode 69, Loss: 1.0602434873580933

tensor(1.0602, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1.,  1., -1.,  0., -1.,  0., -1.],
          [ 0.,  0., -1.,  1.,  1., -1.,  1.,  1.],
          [ 1.,  1.,  1.,  1.,  1., -1., -1.,  0.],
          [-1.,  1.,  0.,  1.,  1.,  0.,  0.,  1.],
          [ 1., -1., -1.,  0.,  0., -1.,  0.,  1.],
          [ 0., -1., -1.,  0., -1., -1., -1., -1.],
          [ 1.,  1., -1., -1.,  1., -1.,  1.,  0.],
          [ 1., -1., -1.,  0.,  0., -1.,  0.,  1.]]]])

1

Episode 70, Loss: 1.059924840927124

tensor(1.0599, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1.,  1.,  1.,  0., -1.,  0., -1.],
          [ 0.,  0., -1.,  1.,  1.,  1.,  1., -1.],
          [ 1.,  1.,  1.,  1.,  1., -1., -1.,  0.],
          [-1.,  1.,  0.,  1., -1.,  0.,  0.,  1.],
          [ 1., -1., -1.,  0.,  0., -1.,  0.,  1.],
          [ 0., -1.,  1.,  0., -1., -1., -1., -1.],
          [ 1.,  1., -1., -1.,  1., -1.,  1.,  0.],
          [ 1., -1., -1.,  0.,  0., -1.,  0., -1.]]]])

1

Episode 71, Loss: 1.0589066743850708

tensor(1.0589, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1.,  1.,  1.,  0., -1.,  0.,  1.],
          [ 1., -1.,  1.,  1.,  1., -1.,  1., -1.],
          [-1.,  1.,  1.,  1.,  1., -1., -1.,  0.],
          [-1.,  1.,  1.,  1., -1., -1.,  0.,  1.],
          [ 1., -1., -1.,  0.,  0., -1., -1.,  1.],
          [ 0.,  1., -1.,  1., -1., -1., -1., -1.],
          [ 1.,  1., -1., -1.,  1., -1.,  1.,  0.],
          [ 1., -1., -1., -1.,  0., -1.,  0., -1.]]]])

-1

Episode 72, Loss: 1.0584458112716675

tensor(1.0584, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1., -1., -1.,  0., -1.,  0.,  1.],
          [ 1., -1.,  1.,  1.,  1., -1.,  1.,  1.],
          [-1.,  1., -1.,  1.,  1.,  1., -1.,  0.],
          [-1.,  1., -1.,  1., -1.,  0.,  0.,  1.],
          [ 1., -1., -1.,  0.,  0., -1., -1.,  1.],
          [ 0.,  1., -1.,  0., -1., -1., -1., -1.],
          [ 1.,  1., -1., -1.,  1., -1.,  1.,  0.],
          [ 1., -1.,  1.,  1.,  0., -1.,  0., -1.]]]])

-1

Episode 73, Loss: 1.0580542087554932

tensor(1.0581, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1.,  1.,  1.,  0.,  1.,  0.,  1.],
          [-1., -1.,  1.,  1., -1., -1.,  1.,  1.],
          [ 1.,  1., -1.,  1.,  1., -1., -1.,  0.],
          [-1.,  1., -1., -1., -1.,  0.,  0.,  1.],
          [ 1., -1., -1.,  0.,  0., -1., -1.,  1.],
          [ 0.,  1., -1.,  0., -1., -1., -1., -1.],
          [ 1.,  1., -1., -1.,  1., -1.,  1.,  0.],
          [ 1., -1.,  1.,  1.,  0., -1.,  0., -1.]]]])

-1

Episode 74, Loss: 1.0579702854156494

tensor(1.0580, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1.,  1., -1.,  0.,  1.,  0.,  1.],
          [-1.,  1.,  1.,  1.,  1., -1.,  1.,  1.],
          [ 1.,  1.,  1.,  1., -1., -1., -1.,  0.],
          [-1.,  1., -1., -1., -1., -1.,  0.,  1.],
          [ 1., -1., -1.,  0.,  0., -1., -1., -1.],
          [ 0.,  1., -1.,  1., -1., -1., -1., -1.],
          [ 1.,  1., -1., -1.,  1., -1.,  1.,  0.],
          [ 1., -1.,  1., -1.,  0.,  1.,  0., -1.]]]])

-1

Episode 75, Loss: 1.0570948123931885

tensor(1.0571, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1.,  1., -1.,  0.,  1.,  0.,  1.],
          [-1.,  1.,  1.,  1.,  1., -1.,  1.,  1.],
          [ 1.,  1.,  1.,  1., -1., -1., -1., -1.],
          [-1.,  1., -1., -1., -1., -1.,  1., -1.],
          [ 1., -1., -1.,  0.,  0., -1.,  1., -1.],
          [ 1.,  1., -1.,  1., -1.,  1., -1., -1.],
          [ 1.,  1., -1., -1.,  1., -1.,  1., -1.],
          [-1., -1.,  1., -1.,  1.,  1., -1., -1.]]]])

-1

Episode 76, Loss: 1.05726158618927

tensor(1.0573, grad_fn=<AddBackward0>)

tensor([[[[-1.,  1.,  1., -1., -1.,  1., -1., -1.],
          [-1., -1.,  1.,  1., -1., -1.,  1.,  1.],
          [ 1.,  1., -1.,  1.,  1.,  1.,  1., -1.],
          [-1.,  1., -1., -1., -1., -1.,  1., -1.],
          [ 1., -1., -1., -1.,  1., -1., -1.,  1.],
          [-1.,  1.,  1.,  1., -1.,  1., -1., -1.],
          [ 1.,  1., -1., -1.,  1., -1.,  1.,  1.],
          [ 1., -1.,  1.,  1.,  1., -1.,  1., -1.]]]])

-1

Episode 77, Loss: 1.0557821989059448

tensor(1.0558, grad_fn=<AddBackward0>)

tensor([[[[-1.,  1.,  1., -1.,  0.,  1.,  0., -1.],
          [ 1., -1.,  1.,  1.,  1., -1.,  1.,  1.],
          [-1.,  1., -1.,  1., -1.,  1.,  1.,  0.],
          [-1.,  1., -1., -1., -1., -1., -1., -1.],
          [ 1., -1., -1.,  0.,  0., -1.,  1., -1.],
          [ 0.,  1.,  1.,  1., -1.,  1., -1., -1.],
          [ 1.,  1., -1., -1.,  1., -1.,  1.,  0.],
          [-1., -1.,  1.,  1.,  0.,  1.,  1., -1.]]]])

-1

Episode 78, Loss: 1.0555851459503174

tensor(1.0556, grad_fn=<AddBackward0>)

tensor([[[[-1.,  1.,  1., -1.,  0.,  1.,  0., -1.],
          [ 0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.],
          [ 0.,  1.,  1.,  1., -1., -1.,  1.,  0.],
          [-1.,  1.,  0., -1., -1.,  0.,  0., -1.],
          [ 1., -1., -1.,  0.,  0., -1., -1., -1.],
          [ 0.,  1.,  1.,  0., -1.,  1., -1., -1.],
          [ 1.,  1., -1., -1.,  1., -1.,  1.,  0.],
          [ 0., -1.,  1.,  0.,  0.,  1.,  0., -1.]]]])

1

Episode 79, Loss: 1.0532594919204712

tensor(1.0533, grad_fn=<AddBackward0>)

tensor([[[[-1.,  1.,  1., -1.,  0.,  1.,  0., -1.],
          [-1.,  1., -1.,  1., -1., -1.,  1.,  1.],
          [ 1.,  1.,  1.,  1., -1., -1.,  1., -1.],
          [-1.,  1., -1., -1., -1., -1.,  1., -1.],
          [ 1., -1., -1.,  1., -1., -1., -1.,  1.],
          [ 1.,  1.,  1.,  1., -1.,  1., -1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1., -1.],
          [ 1., -1.,  1.,  1.,  1.,  1., -1., -1.]]]])

-1

Episode 80, Loss: 1.052209496498108

tensor(1.0522, grad_fn=<AddBackward0>)

tensor([[[[-1.,  1.,  1., -1.,  0., -1.,  0.,  1.],
          [-1.,  1.,  1.,  1., -1., -1.,  1.,  1.],
          [-1.,  1.,  1.,  1., -1., -1.,  1.,  0.],
          [-1.,  1., -1., -1., -1., -1.,  0., -1.],
          [ 1., -1., -1.,  0.,  0., -1., -1.,  1.],
          [ 0.,  1., -1.,  1., -1.,  1.,  1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [ 1., -1.,  1.,  1.,  0.,  1.,  0., -1.]]]])

-1

Episode 81, Loss: 1.0522902011871338

tensor(1.0523, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1.,  1., -1.,  0., -1.,  0.,  1.],
          [ 0.,  0.,  0.,  1., -1., -1.,  1.,  1.],
          [ 0.,  1., -1.,  1., -1., -1.,  1.,  0.],
          [-1.,  1.,  0., -1., -1.,  0.,  0., -1.],
          [ 1., -1., -1.,  0.,  0., -1.,  1.,  1.],
          [ 0., -1., -1.,  0., -1.,  1.,  1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [ 1., -1.,  1.,  0.,  0.,  1.,  0., -1.]]]])

-1

Episode 82, Loss: 1.0520061254501343

tensor(1.0520, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1.,  1., -1.,  0., -1.,  0.,  1.],
          [ 0.,  0.,  0.,  1., -1., -1.,  1.,  1.],
          [ 0.,  1., -1.,  1., -1., -1.,  1.,  0.],
          [-1.,  1.,  0., -1., -1.,  0.,  0., -1.],
          [ 1., -1., -1.,  0.,  0., -1.,  1.,  1.],
          [ 0., -1., -1.,  0., -1.,  1.,  1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [ 1., -1.,  1.,  0.,  0.,  1.,  0., -1.]]]])

-1

Episode 83, Loss: 1.0517480373382568

tensor(1.0517, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1.,  1., -1.,  0., -1.,  0.,  1.],
          [ 0.,  0.,  0.,  1., -1., -1.,  1.,  1.],
          [ 0.,  1.,  1.,  1., -1., -1., -1.,  0.],
          [-1.,  1.,  0., -1., -1.,  0.,  0., -1.],
          [ 1., -1., -1.,  0.,  0., -1.,  1.,  1.],
          [ 0., -1., -1.,  0., -1.,  1.,  1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [ 1., -1.,  1.,  0.,  0.,  1.,  0., -1.]]]])

-1

Episode 84, Loss: 1.0492331981658936

tensor(1.0492, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1.,  1., -1.,  0., -1.,  0.,  1.],
          [ 0.,  0.,  0.,  1., -1., -1.,  1.,  1.],
          [ 0.,  1.,  1.,  1., -1., -1., -1.,  0.],
          [-1.,  1.,  0., -1., -1.,  0.,  0., -1.],
          [ 1., -1., -1.,  0.,  0., -1.,  1.,  1.],
          [ 0., -1., -1.,  0., -1.,  1.,  1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [ 1., -1.,  1.,  0.,  0.,  1.,  0., -1.]]]])

-1

Episode 85, Loss: 1.0491726398468018

tensor(1.0492, grad_fn=<AddBackward0>)

tensor([[[[-1.,  1.,  1., -1.,  0., -1.,  0.,  1.],
          [ 0.,  0.,  0.,  1., -1., -1.,  1.,  1.],
          [ 0.,  1.,  1.,  1., -1., -1.,  1.,  0.],
          [-1.,  1.,  0., -1., -1.,  0.,  0., -1.],
          [ 1., -1., -1.,  0.,  0., -1.,  1.,  1.],
          [ 0., -1., -1.,  0., -1.,  1.,  1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [ 1., -1.,  1.,  0.,  0.,  1.,  0., -1.]]]])

-1

Episode 86, Loss: 1.0489550828933716

tensor(1.0490, grad_fn=<AddBackward0>)

tensor([[[[-1.,  1.,  1., -1.,  0., -1.,  0.,  1.],
          [ 0.,  0.,  0.,  1., -1., -1.,  1.,  1.],
          [ 0.,  1.,  1.,  1., -1., -1.,  1.,  0.],
          [-1.,  1.,  0., -1., -1.,  0.,  0., -1.],
          [ 1., -1., -1.,  0.,  0., -1.,  1.,  1.],
          [ 0., -1., -1.,  0., -1.,  1.,  1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [ 1., -1.,  1.,  0.,  0.,  1.,  0., -1.]]]])

-1

Episode 87, Loss: 1.046114444732666

tensor(1.0461, grad_fn=<AddBackward0>)

tensor([[[[-1.,  1.,  1., -1.,  0., -1.,  0.,  1.],
          [-1.,  1.,  0.,  1.,  1., -1.,  1.,  1.],
          [ 1.,  1.,  1.,  1., -1., -1.,  1.,  0.],
          [-1.,  1., -1., -1., -1., -1.,  0., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  1.,  1.],
          [ 0., -1., -1.,  0., -1.,  1.,  1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [ 1., -1.,  1.,  1.,  0., -1.,  0., -1.]]]])

-1

Episode 88, Loss: 1.0448846817016602

tensor(1.0449, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1.,  1., -1.,  0., -1.,  0.,  1.],
          [ 1., -1., -1.,  1., -1.,  1.,  1.,  1.],
          [-1.,  1.,  1.,  1., -1., -1., -1.,  0.],
          [-1.,  1., -1., -1., -1.,  1.,  0., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  1.,  1.],
          [-1., -1., -1., -1., -1.,  1.,  1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [ 1., -1.,  1.,  1.,  0.,  1.,  1., -1.]]]])

-1

Episode 89, Loss: 1.044588327407837

tensor(1.0446, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1.,  1., -1.,  0.,  1.,  0.,  1.],
          [ 1., -1., -1.,  1., -1.,  1.,  1.,  1.],
          [-1.,  1.,  1., -1., -1., -1., -1.,  0.],
          [-1.,  1., -1., -1., -1.,  1.,  0., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  1.,  1.],
          [-1., -1., -1., -1., -1.,  1.,  1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [ 1., -1.,  1.,  1.,  0.,  1.,  1., -1.]]]])

-1

Episode 90, Loss: 1.0426045656204224

tensor(1.0426, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1.,  1., -1.,  0.,  1.,  0.,  1.],
          [ 1., -1., -1.,  1., -1.,  1.,  1.,  1.],
          [-1.,  1.,  1., -1., -1., -1., -1.,  0.],
          [-1.,  1., -1., -1., -1.,  1.,  0., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  1.,  1.],
          [-1., -1., -1., -1., -1.,  1.,  1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [ 1., -1.,  1.,  1.,  0.,  1.,  1., -1.]]]])

-1

Episode 91, Loss: 1.0415294170379639

tensor(1.0415, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1.,  1., -1.,  0.,  1.,  0.,  1.],
          [ 0., -1.,  0.,  1.,  1.,  1.,  1.,  1.],
          [ 0.,  1.,  1., -1., -1., -1., -1.,  0.],
          [-1.,  1.,  0., -1., -1.,  0.,  0., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  1.,  1.],
          [ 0., -1., -1.,  0., -1.,  1.,  1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [ 1., -1.,  1.,  0.,  0., -1.,  0., -1.]]]])

1

Episode 92, Loss: 1.0401530265808105

tensor(1.0402, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1.,  1., -1.,  0.,  1.,  0.,  1.],
          [ 0., -1.,  0.,  1.,  1.,  1.,  1.,  1.],
          [ 0.,  1.,  1., -1., -1., -1., -1.,  0.],
          [-1.,  1.,  0., -1., -1.,  0.,  0., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  1.,  1.],
          [ 0., -1., -1.,  0., -1.,  1.,  1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [ 1., -1.,  1.,  0.,  0., -1.,  0., -1.]]]])

1

Episode 93, Loss: 1.0375304222106934

tensor(1.0375, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1.,  1., -1.,  0.,  1.,  0.,  1.],
          [ 1., -1.,  0.,  1., -1.,  1.,  1.,  1.],
          [-1.,  1.,  1.,  1., -1., -1., -1.,  0.],
          [-1.,  1., -1., -1., -1., -1.,  0., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  1.,  1.],
          [ 0., -1., -1.,  1., -1.,  1., -1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [ 1., -1.,  1.,  1.,  0.,  1.,  0., -1.]]]])

1

Episode 94, Loss: 1.0365005731582642

tensor(1.0365, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1.,  1., -1.,  0.,  1.,  0.,  1.],
          [ 1., -1.,  0.,  1., -1.,  1.,  1.,  1.],
          [-1.,  1.,  1.,  1., -1., -1., -1.,  0.],
          [-1.,  1., -1., -1., -1., -1.,  0., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  1.,  1.],
          [ 0., -1., -1.,  1., -1.,  1., -1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [ 1., -1.,  1.,  1.,  0.,  1.,  0., -1.]]]])

1

Episode 95, Loss: 1.0344072580337524

tensor(1.0344, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1.,  1., -1.,  0.,  1.,  0.,  1.],
          [ 1., -1.,  0.,  1., -1.,  1.,  1.,  1.],
          [-1.,  1.,  1., -1.,  1., -1., -1.,  0.],
          [-1.,  1., -1., -1., -1., -1.,  0., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  1.,  1.],
          [ 0., -1., -1.,  1., -1.,  1., -1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [ 1., -1.,  1.,  1.,  0.,  1.,  0., -1.]]]])

1

Episode 96, Loss: 1.03188955783844

tensor(1.0319, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1.,  1., -1.,  0., -1.,  0.,  1.],
          [ 1., -1.,  0.,  1.,  1., -1.,  1.,  1.],
          [ 1.,  1.,  1., -1.,  1., -1., -1.,  0.],
          [-1.,  1., -1., -1., -1.,  1.,  0., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  1.,  1.],
          [ 0., -1., -1.,  0., -1.,  1.,  1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [ 1., -1.,  1.,  0.,  0., -1.,  0., -1.]]]])

1

Episode 97, Loss: 1.0303261280059814

tensor(1.0303, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1.,  1., -1.,  0., -1.,  0.,  1.],
          [ 1., -1.,  0.,  1.,  1., -1.,  1.,  1.],
          [ 1.,  1.,  1., -1.,  1., -1., -1.,  0.],
          [-1.,  1., -1., -1., -1.,  1.,  0., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  1.,  1.],
          [ 0., -1., -1.,  0., -1.,  1.,  1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [ 1., -1.,  1.,  0.,  0., -1.,  0., -1.]]]])

1

Episode 98, Loss: 1.0277526378631592

tensor(1.0278, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1.,  1., -1.,  0., -1.,  0.,  1.],
          [ 1., -1.,  0.,  1.,  1., -1.,  1.,  1.],
          [ 1.,  1.,  1., -1.,  1., -1., -1.,  0.],
          [-1.,  1., -1., -1., -1.,  1.,  0., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  1.,  1.],
          [ 0., -1., -1.,  0., -1.,  1., -1.,  1.],
          [ 1., -1., -1.,  1.,  1., -1.,  1.,  0.],
          [ 1., -1.,  1.,  0.,  0., -1.,  0., -1.]]]])

1

Episode 99, Loss: 1.0270696878433228

tensor(1.0271, grad_fn=<AddBackward0>)

tensor([[[[ 1.,  1.,  1., -1.,  0.,  1.,  0., -1.],
          [-1., -1.,  0.,  1., -1., -1.,  1.,  1.],
          [ 1.,  1.,  1., -1.,  1., -1., -1.,  0.],
          [-1.,  1.,  1., -1., -1.,  1.,  0., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  1.,  1.],
          [ 0., -1., -1.,  0., -1.,  1., -1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [ 1., -1.,  1.,  0.,  0.,  1.,  0.,  1.]]]])

1

In [10]:
# state.get_legal_actions()

## MCTS Inference

In [11]:
# 使用示例
state = GomokuState(board_size=board_size, gomoku_number=gomoku_number)
while not state.is_terminal():
    action = mcts_move(state, net)
    state.move(action)
    print(state.board)
print("Game over")
state.get_reward()

tensor([[[[0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 1., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0.]]]])

tensor([[[[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0., -1.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0., -1.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0., -1.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0., -1.,  0.,  0.,  0.],
          [ 0.,  0., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0., -1.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0., -1.,  1.,  0.,  0.],
          [ 0.,  0., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0., -1.,  0.,  0.,  0., -1.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0., -1.,  1.,  0.,  0.],
          [ 0.,  0., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  1.,  0., -1.,  0.,  0.,  0., -1.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0., -1.,  1.,  0.,  0.],
          [ 0.,  0., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  1.,  0., -1.,  0.,  0.,  0., -1.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0., -1.,  1.,  0.,  0.],
          [ 0., -1., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  1.,  0., -1.,  0.,  0.,  0., -1.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0., -1.,  1.,  0.,  1.],
          [ 0., -1., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [-1.,  1.,  0., -1.,  0.,  0.,  0., -1.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0., -1.,  1.,  0.,  1.],
          [ 0., -1., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [-1.,  1.,  0., -1.,  0.,  0.,  0., -1.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0., -1.,  1.,  0.,  1.],
          [ 0., -1., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[ 0.,  0.,  1., -1.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [-1.,  1.,  0., -1.,  0.,  0.,  0., -1.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0., -1.,  1.,  0.,  1.],
          [ 0., -1., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[ 1.,  0.,  1., -1.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [-1.,  1.,  0., -1.,  0.,  0.,  0., -1.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0., -1.,  1.,  0.,  1.],
          [ 0., -1., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[ 1.,  0.,  1., -1.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0., -1.,  0.],
          [-1.,  1.,  0., -1.,  0.,  0.,  0., -1.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0., -1.,  1.,  0.,  1.],
          [ 0., -1., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[ 1.,  0.,  1., -1.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  0., -1.,  0.],
          [-1.,  1.,  0., -1.,  0.,  0.,  0., -1.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0., -1.,  1.,  0.,  1.],
          [ 0., -1., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[ 1.,  0.,  1., -1.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0., -1., -1.,  0.],
          [-1.,  1.,  0., -1.,  0.,  0.,  0., -1.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0., -1.,  1.,  0.,  1.],
          [ 0., -1., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[ 1.,  0.,  1., -1.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.],
          [ 0.,  0.,  1.,  0.,  0., -1., -1.,  0.],
          [-1.,  1.,  0., -1.,  0.,  0.,  0., -1.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0., -1.,  1.,  0.,  1.],
          [ 0., -1., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[ 1.,  0.,  1., -1.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.],
          [ 0.,  0.,  1.,  0.,  0., -1., -1.,  0.],
          [-1.,  1.,  0., -1.,  0.,  0.,  0., -1.],
          [ 0.,  0.,  0.,  0.,  0., -1.,  0.,  0.],
          [ 0.,  0.,  0.,  0., -1.,  1.,  0.,  1.],
          [ 0., -1., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[ 1.,  0.,  1., -1.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.],
          [ 0.,  0.,  1.,  0.,  0., -1., -1.,  0.],
          [-1.,  1.,  0., -1.,  0.,  0.,  0., -1.],
          [ 0.,  0.,  0.,  0.,  0., -1.,  0.,  0.],
          [ 0.,  0.,  0.,  0., -1.,  1.,  0.,  1.],
          [ 1., -1., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[ 1.,  0.,  1., -1.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.],
          [ 0.,  0.,  1.,  0.,  0., -1., -1.,  0.],
          [-1.,  1.,  0., -1.,  0.,  0.,  0., -1.],
          [-1.,  0.,  0.,  0.,  0., -1.,  0.,  0.],
          [ 0.,  0.,  0.,  0., -1.,  1.,  0.,  1.],
          [ 1., -1., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[ 1.,  0.,  1., -1.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.],
          [ 0.,  0.,  1.,  0.,  0., -1., -1.,  0.],
          [-1.,  1.,  0., -1.,  0.,  0.,  0., -1.],
          [-1.,  0.,  1.,  0.,  0., -1.,  0.,  0.],
          [ 0.,  0.,  0.,  0., -1.,  1.,  0.,  1.],
          [ 1., -1., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[ 1.,  0.,  1., -1.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.],
          [ 0.,  0.,  1.,  0.,  0., -1., -1.,  0.],
          [-1.,  1.,  0., -1.,  0.,  0.,  0., -1.],
          [-1.,  0.,  1.,  0.,  0., -1.,  0.,  0.],
          [ 0.,  0., -1.,  0., -1.,  1.,  0.,  1.],
          [ 1., -1., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[ 1.,  0.,  1., -1.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.],
          [ 0.,  0.,  1.,  0.,  0., -1., -1.,  0.],
          [-1.,  1.,  0., -1.,  0.,  0.,  0., -1.],
          [-1.,  0.,  1.,  0.,  0., -1.,  0.,  0.],
          [ 0.,  0., -1.,  0., -1.,  1.,  0.,  1.],
          [ 1., -1., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.]]]])

tensor([[[[ 1.,  0.,  1., -1.,  0.,  0.,  0., -1.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.],
          [ 0.,  0.,  1.,  0.,  0., -1., -1.,  0.],
          [-1.,  1.,  0., -1.,  0.,  0.,  0., -1.],
          [-1.,  0.,  1.,  0.,  0., -1.,  0.,  0.],
          [ 0.,  0., -1.,  0., -1.,  1.,  0.,  1.],
          [ 1., -1., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.]]]])

tensor([[[[ 1.,  0.,  1., -1.,  0.,  0.,  0., -1.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.],
          [ 0.,  1.,  1.,  0.,  0., -1., -1.,  0.],
          [-1.,  1.,  0., -1.,  0.,  0.,  0., -1.],
          [-1.,  0.,  1.,  0.,  0., -1.,  0.,  0.],
          [ 0.,  0., -1.,  0., -1.,  1.,  0.,  1.],
          [ 1., -1., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.]]]])

tensor([[[[ 1.,  0.,  1., -1.,  0.,  0.,  0., -1.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.],
          [ 0.,  1.,  1.,  0.,  0., -1., -1.,  0.],
          [-1.,  1.,  0., -1.,  0.,  0.,  0., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  0.,  0.],
          [ 0.,  0., -1.,  0., -1.,  1.,  0.,  1.],
          [ 1., -1., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.]]]])

tensor([[[[ 1.,  0.,  1., -1.,  0.,  0.,  0., -1.],
          [ 0.,  0.,  0.,  1.,  0.,  0.,  1.,  1.],
          [ 0.,  1.,  1.,  0.,  0., -1., -1.,  0.],
          [-1.,  1.,  0., -1.,  0.,  0.,  0., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  0.,  0.],
          [ 0.,  0., -1.,  0., -1.,  1.,  0.,  1.],
          [ 1., -1., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.]]]])

tensor([[[[ 1.,  0.,  1., -1.,  0.,  0.,  0., -1.],
          [ 0.,  0.,  0.,  1.,  0.,  0.,  1.,  1.],
          [ 0.,  1.,  1.,  0.,  0., -1., -1.,  0.],
          [-1.,  1.,  0., -1.,  0.,  0.,  0., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  0.,  0.],
          [ 0.,  0., -1.,  0., -1.,  1.,  0.,  1.],
          [ 1., -1., -1.,  0.,  0., -1.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.]]]])

tensor([[[[ 1.,  0.,  1., -1.,  0.,  0.,  0., -1.],
          [ 0.,  0.,  0.,  1.,  0.,  0.,  1.,  1.],
          [ 0.,  1.,  1.,  0.,  0., -1., -1.,  0.],
          [-1.,  1.,  0., -1.,  0.,  0.,  0., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  0.,  0.],
          [ 0.,  0., -1.,  0., -1.,  1.,  0.,  1.],
          [ 1., -1., -1.,  0.,  1., -1.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.]]]])

tensor([[[[ 1.,  0.,  1., -1.,  0.,  0.,  0., -1.],
          [ 0.,  0.,  0.,  1.,  0.,  0.,  1.,  1.],
          [ 0.,  1.,  1.,  0.,  0., -1., -1.,  0.],
          [-1.,  1.,  0., -1.,  0.,  0.,  0., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  0.,  0.],
          [ 0.,  0., -1.,  0., -1.,  1., -1.,  1.],
          [ 1., -1., -1.,  0.,  1., -1.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.]]]])

tensor([[[[ 1.,  0.,  1., -1.,  0.,  1.,  0., -1.],
          [ 0.,  0.,  0.,  1.,  0.,  0.,  1.,  1.],
          [ 0.,  1.,  1.,  0.,  0., -1., -1.,  0.],
          [-1.,  1.,  0., -1.,  0.,  0.,  0., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  0.,  0.],
          [ 0.,  0., -1.,  0., -1.,  1., -1.,  1.],
          [ 1., -1., -1.,  0.,  1., -1.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.]]]])

tensor([[[[ 1.,  0.,  1., -1.,  0.,  1.,  0., -1.],
          [ 0.,  0.,  0.,  1.,  0.,  0.,  1.,  1.],
          [ 0.,  1.,  1.,  0.,  0., -1., -1.,  0.],
          [-1.,  1.,  0., -1.,  0.,  0.,  0., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  0.,  0.],
          [ 0.,  0., -1.,  0., -1.,  1., -1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.]]]])

tensor([[[[ 1.,  0.,  1., -1.,  0.,  1.,  0., -1.],
          [ 0.,  0.,  0.,  1.,  0.,  0.,  1.,  1.],
          [ 0.,  1.,  1.,  0.,  1., -1., -1.,  0.],
          [-1.,  1.,  0., -1.,  0.,  0.,  0., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  0.,  0.],
          [ 0.,  0., -1.,  0., -1.,  1., -1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.]]]])

tensor([[[[ 1.,  0.,  1., -1.,  0.,  1.,  0., -1.],
          [ 0.,  0.,  0.,  1.,  0.,  0.,  1.,  1.],
          [ 0.,  1.,  1., -1.,  1., -1., -1.,  0.],
          [-1.,  1.,  0., -1.,  0.,  0.,  0., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  0.,  0.],
          [ 0.,  0., -1.,  0., -1.,  1., -1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.]]]])

tensor([[[[ 1.,  0.,  1., -1.,  0.,  1.,  0., -1.],
          [ 0.,  0.,  0.,  1.,  0.,  0.,  1.,  1.],
          [ 0.,  1.,  1., -1.,  1., -1., -1.,  0.],
          [-1.,  1.,  0., -1.,  0.,  0.,  0., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  0.,  1.],
          [ 0.,  0., -1.,  0., -1.,  1., -1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.]]]])

tensor([[[[ 1.,  0.,  1., -1.,  0.,  1.,  0., -1.],
          [ 0.,  0.,  0.,  1., -1.,  0.,  1.,  1.],
          [ 0.,  1.,  1., -1.,  1., -1., -1.,  0.],
          [-1.,  1.,  0., -1.,  0.,  0.,  0., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  0.,  1.],
          [ 0.,  0., -1.,  0., -1.,  1., -1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.]]]])

tensor([[[[ 1.,  0.,  1., -1.,  0.,  1.,  0., -1.],
          [ 0.,  0.,  0.,  1., -1.,  0.,  1.,  1.],
          [ 0.,  1.,  1., -1.,  1., -1., -1.,  0.],
          [-1.,  1.,  0., -1.,  0.,  0.,  0., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  0.,  1.],
          [ 0.,  0., -1.,  0., -1.,  1., -1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [ 0.,  0.,  1.,  0.,  0.,  1.,  0.,  1.]]]])

tensor([[[[ 1.,  0.,  1., -1.,  0.,  1.,  0., -1.],
          [ 0.,  0.,  0.,  1., -1.,  0.,  1.,  1.],
          [ 0.,  1.,  1., -1.,  1., -1., -1.,  0.],
          [-1.,  1.,  0., -1.,  0.,  0.,  0., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  0.,  1.],
          [ 0.,  0., -1.,  0., -1.,  1., -1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [ 0., -1.,  1.,  0.,  0.,  1.,  0.,  1.]]]])

tensor([[[[ 1.,  1.,  1., -1.,  0.,  1.,  0., -1.],
          [ 0.,  0.,  0.,  1., -1.,  0.,  1.,  1.],
          [ 0.,  1.,  1., -1.,  1., -1., -1.,  0.],
          [-1.,  1.,  0., -1.,  0.,  0.,  0., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  0.,  1.],
          [ 0.,  0., -1.,  0., -1.,  1., -1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [ 0., -1.,  1.,  0.,  0.,  1.,  0.,  1.]]]])

tensor([[[[ 1.,  1.,  1., -1.,  0.,  1.,  0., -1.],
          [ 0.,  0.,  0.,  1., -1.,  0.,  1.,  1.],
          [ 0.,  1.,  1., -1.,  1., -1., -1.,  0.],
          [-1.,  1.,  0., -1., -1.,  0.,  0., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  0.,  1.],
          [ 0.,  0., -1.,  0., -1.,  1., -1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [ 0., -1.,  1.,  0.,  0.,  1.,  0.,  1.]]]])

tensor([[[[ 1.,  1.,  1., -1.,  0.,  1.,  0., -1.],
          [ 0.,  0.,  0.,  1., -1.,  0.,  1.,  1.],
          [ 0.,  1.,  1., -1.,  1., -1., -1.,  0.],
          [-1.,  1.,  0., -1., -1.,  0.,  0., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  1.,  1.],
          [ 0.,  0., -1.,  0., -1.,  1., -1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [ 0., -1.,  1.,  0.,  0.,  1.,  0.,  1.]]]])

tensor([[[[ 1.,  1.,  1., -1.,  0.,  1.,  0., -1.],
          [ 0.,  0.,  0.,  1., -1.,  0.,  1.,  1.],
          [ 0.,  1.,  1., -1.,  1., -1., -1.,  0.],
          [-1.,  1.,  0., -1., -1.,  0.,  0., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  1.,  1.],
          [ 0., -1., -1.,  0., -1.,  1., -1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [ 0., -1.,  1.,  0.,  0.,  1.,  0.,  1.]]]])

tensor([[[[ 1.,  1.,  1., -1.,  0.,  1.,  0., -1.],
          [ 0.,  0.,  0.,  1., -1.,  0.,  1.,  1.],
          [ 0.,  1.,  1., -1.,  1., -1., -1.,  0.],
          [-1.,  1.,  0., -1., -1.,  0.,  0., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  1.,  1.],
          [ 0., -1., -1.,  0., -1.,  1., -1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [ 1., -1.,  1.,  0.,  0.,  1.,  0.,  1.]]]])

tensor([[[[ 1.,  1.,  1., -1.,  0.,  1.,  0., -1.],
          [ 0., -1.,  0.,  1., -1.,  0.,  1.,  1.],
          [ 0.,  1.,  1., -1.,  1., -1., -1.,  0.],
          [-1.,  1.,  0., -1., -1.,  0.,  0., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  1.,  1.],
          [ 0., -1., -1.,  0., -1.,  1., -1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [ 1., -1.,  1.,  0.,  0.,  1.,  0.,  1.]]]])

tensor([[[[ 1.,  1.,  1., -1.,  0.,  1.,  0., -1.],
          [ 0., -1.,  0.,  1., -1.,  0.,  1.,  1.],
          [ 1.,  1.,  1., -1.,  1., -1., -1.,  0.],
          [-1.,  1.,  0., -1., -1.,  0.,  0., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  1.,  1.],
          [ 0., -1., -1.,  0., -1.,  1., -1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [ 1., -1.,  1.,  0.,  0.,  1.,  0.,  1.]]]])

tensor([[[[ 1.,  1.,  1., -1.,  0.,  1.,  0., -1.],
          [ 0., -1.,  0.,  1., -1., -1.,  1.,  1.],
          [ 1.,  1.,  1., -1.,  1., -1., -1.,  0.],
          [-1.,  1.,  0., -1., -1.,  0.,  0., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  1.,  1.],
          [ 0., -1., -1.,  0., -1.,  1., -1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [ 1., -1.,  1.,  0.,  0.,  1.,  0.,  1.]]]])

tensor([[[[ 1.,  1.,  1., -1.,  0.,  1.,  0., -1.],
          [ 1., -1.,  0.,  1., -1., -1.,  1.,  1.],
          [ 1.,  1.,  1., -1.,  1., -1., -1.,  0.],
          [-1.,  1.,  0., -1., -1.,  0.,  0., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  1.,  1.],
          [ 0., -1., -1.,  0., -1.,  1., -1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [ 1., -1.,  1.,  0.,  0.,  1.,  0.,  1.]]]])

tensor([[[[ 1.,  1.,  1., -1.,  0.,  1.,  0., -1.],
          [ 1., -1.,  0.,  1., -1., -1.,  1.,  1.],
          [ 1.,  1.,  1., -1.,  1., -1., -1.,  0.],
          [-1.,  1., -1., -1., -1.,  0.,  0., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  1.,  1.],
          [ 0., -1., -1.,  0., -1.,  1., -1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [ 1., -1.,  1.,  0.,  0.,  1.,  0.,  1.]]]])

tensor([[[[ 1.,  1.,  1., -1.,  0.,  1.,  0., -1.],
          [ 1., -1.,  0.,  1., -1., -1.,  1.,  1.],
          [ 1.,  1.,  1., -1.,  1., -1., -1.,  0.],
          [-1.,  1., -1., -1., -1.,  1.,  0., -1.],
          [-1., -1.,  1.,  0.,  0., -1.,  1.,  1.],
          [ 0., -1., -1.,  0., -1.,  1., -1.,  1.],
          [ 1., -1., -1., -1.,  1., -1.,  1.,  0.],
          [ 1., -1.,  1.,  0.,  0.,  1.,  0.,  1.]]]])

Game over

1

## MCTS与LLM关系

1. 区别于cartpole，这里的agent在下子时有policy network和value network。
2. 这里要求value估计接近树回溯值
3. 棋子的状态可以看成是连续的(2d棋盘有-1,0,1)，棋子的动作看成是有限的离散集合（动作范围15*15）。
4. LLM的状态是连续的。动作是离散的(词表大小）。这里的问题在于搜索空间更大如llama3为128k
5. LLM与go之间的差异在于，以逐个token来采集，模拟采样的成本过高，且高效采样到terminal成功的难度大，导致有效feedback太少。
6. 如何减少模拟采样的成本，如何有效的采样的正确的推理step，如何得到准确的feedback，是LLM做MCTS-like搜索的关键。
7. 针对6如何来解决？ 

reference：claude-3.5-sonnet