# Gomoku MCTS Pytorch

Author xiaodongguaAIGC

五子棋 MCTS算法实现。代码实现follow AlphaGo-Zero

- agent带policy/value 网络
- 实现了state、node管理
- 实现了从零对弈
- 实现了policy/value损失
- 实现了mcts推理
- 阐述了LLM与MCTS的gap


In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import math
import random
import copy

## config

In [2]:
board_size = 8
channel = 64
gomoku_number = 5  # 多少子连成一条线就算赢
exapand_size = 10
print(f'走子动作集合为:{board_size*board_size}')

走子动作集合为:64

## Gomoku Policy & Value Net Work

In [3]:
class GomokuNet(nn.Module):
    def __init__(self, board_size=15, channel=64):
        super(GomokuNet, self).__init__()
        self.board_size = board_size
        self.channel = channel
        self.conv1 = nn.Conv2d(1, 32, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(32, channel, kernel_size=3, padding=1)
        self.fc1 = nn.Linear(channel * board_size * board_size, channel)
        self.fc2 = nn.Linear(channel, board_size * board_size)
        self.fc3 = nn.Linear(channel, 1)

    def forward(self, x):
        x1 = torch.relu(self.conv1(x))
        x2 = torch.relu(self.conv2(x1))
        x3 = x2.view(-1, self.channel * self.board_size * self.board_size)
        x4 = torch.relu(self.fc1(x3))
        policy = self.fc2(x4)
        value = torch.tanh(self.fc3(x4))
        return policy, value


model = GomokuNet(board_size=board_size, channel=channel)
# data = torch.zeros((1, 1, board_size, board_size), dtype=torch.float32)
# data = torch.randint(high = 2,size=(1, 1, board_size, board_size), dtype=torch.float32)
data = torch.randint(high=2, size=(
    1, 1, board_size, board_size), dtype=torch.float32)
policy, value = model(data)
print(policy.shape)
print(value.shape)

loss = policy[0].mean()
loss.backward()

torch.Size([1, 64])

torch.Size([1, 1])

## Mento Carlo Tree Searching

MCTS state

In [4]:
# 盘面数据
class GomokuState:
    def __init__(self, board_size=15, gomoku_number=4):
        self.board_size = board_size
        self.gomoku_number = gomoku_number

        # 盘面数据里每个格子的数据只有0(空)，1(我方)， 0(对方)
        self.board = torch.zeros(
            (1, 1, board_size, board_size), dtype=torch.float32)
        self.current_player = 1
        self.last_move = None

    def get_legal_actions(self):
        return torch.nonzero(self.board.view(-1) == 0).view(-1)
        # return torch.nonzero(self.board_int.view(-1) == 0)

    def is_terminal(self):
        # gomoku_number = 3
        if self.last_move is None:
            return False
        x, y = self.last_move
        player = self.board[0, 0, x, y]
        directions = [(1, 0), (0, 1), (1, 1), (1, -1)]
        for dx, dy in directions:
            count = 1
            for i in range(1, self.gomoku_number):
                nx, ny = x + i*dx, y + i*dy
                if 0 <= nx < self.board_size and 0 <= ny < self.board_size and self.board[0, 0, nx, ny] == player:
                    count += 1
                else:
                    break
            for i in range(1, gomoku_number):
                nx, ny = x - i*dx, y - i*dy
                if 0 <= nx < self.board_size and 0 <= ny < self.board_size and self.board[0, 0, nx, ny] == player:
                    count += 1
                else:
                    break
            if count >= self.gomoku_number:
                return True
        return len(self.get_legal_actions()) == 0

    def get_reward(self):
        if self.is_terminal():
            if self.current_player == -1:
                return 1  # Previous player (1) won
            else:
                return -1  # Previous player (-1) won
        return 0  # Game not finished

    # 对于盘面，是来回下子的，我方下子为1，对方下子为-1
    def move(self, action):
        x, y = action
        # 一定要clone，不然这里会变成in-place操作
        # 比如 t时刻 board^(t)， t时刻走子 board[0,0,x,y]=1
        # 那么在t时刻的board的数据就被替换了，将导致无法backward
        self.board = self.board.clone()
        # self.board[0, 0, x, y] = torch.tensor(self.current_player)
        # self.current_player = -torch.tensor(self.current_player)
        self.board[0, 0, x, y] = self.current_player
        self.current_player = -self.current_player
        self.last_move = action

    def clone(self):
        new_state = GomokuState(self.board_size)
        new_state.board = self.board.clone()
        new_state.current_player = self.current_player
        new_state.last_move = self.last_move
        return new_state


state = GomokuState(board_size=board_size, gomoku_number=gomoku_number)
print(f'可走子的策略为:{len(state.get_legal_actions())}')
# print(f'可走子的策略为:{state.get_legal_actions()}')

# 走子
state.move([0, 0])  # 我方
state.move([4, 0])  # 对手
state.move([0, 1])
state.move([4, 1])
print(f'是否终止:{state.is_terminal()}')
print(f'奖励:{state.get_reward()}')

state.move([0, 2])
state.move([4, 2])
state.move([0, 3])
state.move([4, 3])
state.move([0, 4])
# state.move([10,4])
print(f'是否终止:{state.is_terminal()}')
print(f'奖励:{state.get_reward()}')

可走子的策略为:64

是否终止:False

奖励:0

是否终止:True

奖励:1

In [5]:
# state = GomokuState(board_size=board_size)
print(f'可走子的策略为:{len(state.get_legal_actions())}')
print(f'可走子的策略为:{state.get_legal_actions()}')

可走子的策略为:55

可走子的策略为:tensor([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
        23, 24, 25, 26, 27, 28, 29, 30, 31, 36, 37, 38, 39, 40, 41, 42, 43, 44,
        45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62,
        63])

### MCTS Node

In [6]:
class MCTSNode:
    def __init__(self, state, parent=None):
        self.state = state
        self.parent = parent
        self.children = {}
        self.visits = 0
        self.value = 0
        self.prior = 0

    def is_fully_expanded(self):
        return len(self.children) == len(self.state.get_legal_actions())

    def is_part_expanded(self):
        return len(self.children) == 10

    def select_child(self):
        return max(self.children.items(), key=lambda x: x[1].uct_value())

    def expand(self, policy):
        # 一次拓展
        valid_actions = self.state.get_legal_actions()
        policy_mask = policy[0, valid_actions]
        
        max_value, max_index = torch.max(policy_mask, dim=0)
        
        id = valid_actions[max_index].item()
        action = [int(id/self.state.board_size),
                  int(id % self.state.board_size)]

        # action = [3,3]
        # id = 12

        child_state = self.state.clone()
        child_state.board.detach()
        child_state.move(action)
        child_node = MCTSNode(child_state, self)
        child_node.prior = policy[0, id]         
        self.children[tuple(action)] = child_node
        return child_node

    def backpropagate(self, value):
        self.visits = self.visits + 1
        self.value = self.value + value
        if self.parent:
            self.parent.backpropagate(-value)

    def uct_value(self, c=1.4):
        if self.visits == 0:
            return float('inf')
        q = self.value / self.visits
        u = c * self.prior * math.sqrt(self.parent.visits) / (1 + self.visits)
        return q + u


state = GomokuState(board_size=board_size)
# 走子
state.move([0, 0])  # 我方
state.move([4, 0])  # 对手
state.move([0, 1])
state.move([4, 1])

node = MCTSNode(state)
policy, value = model(state.board)
print(policy.shape)
# policy2d = policy[0].view(board_size, board_size)
node.expand(policy)
node.backpropagate(2)
loss = (policy**2).mean()
loss.backward()
print(node.state.board)

torch.Size([1, 64])

tensor([[[[ 1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [-1., -1.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]]])

In [7]:
print(node)
print(node.children)
# print(node.children[(3,2)])

<__main__.MCTSNode object at 0x126ca4bd0>

{(3, 4): <__main__.MCTSNode object at 0x10eaa4bd0>}

### MCTS Move

In [8]:
def mcts_move(state, net, num_simulations=1000):
    root = MCTSNode(state)
    for i in range(num_simulations):
        node = root

        # selection use UCB
        while len(node.children) != 0:
            node = node.select_child()[1] 
              
        # expansion
        if len(node.state.get_legal_actions()) != 0 and not node.state.is_terminal():
            policy, _ = net(node.state.board)
            policy = torch.softmax(policy, dim=1,) 
            node = node.expand(policy)   
                
        value = node.state.get_reward()
        if value == 0:  # If the game is not finished, use the neural network's evaluation
            _, value = net(node.state.board)
            value = value.item()  # 估计谁能赢

        # backup
        node.backpropagate(value)

    return max(root.children.items(), key=lambda x: x[1].visits)[0] # 实际选择执行的动作


a = mcts_move(state, model, num_simulations=10)
state.move(a)
final_reward = state.get_reward()
policy, _ = model(state.board)
loss = (policy**2).mean()*final_reward
loss.backward()
print(node.state.board)

tensor([[[[ 1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
          [-1., -1.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]]])

## MCTS Training

In [12]:
# torch.autograd.set_detect_anomaly(True)
# 初始化神经网络
net = GomokuNet(board_size=board_size, channel=channel)
optimizer = optim.Adam(net.parameters(), lr=0.001)

episodes = 200
mcts_simulations = 1000

# 训练循环
for episode in range(episodes):  # 这个循环是用于训练 policy/value network
    state = GomokuState(board_size=board_size,
                        gomoku_number=gomoku_number)  
    states, policies, values, actions = [], [], [], []

    # t1:
    # 做MCTS 100次
    # 选出一个下子步骤
    # t2:
    # 做MCTS 100次
    # 选出一个下子步骤
    while not state.is_terminal():
        # if True:
        policy, value = net(state.board)  # 采样策略和价值估计
        policy = torch.softmax(policy, dim=1)

        # 模拟盘数
        action = mcts_move(state, net, mcts_simulations)  # mcts拓展 # 100次MCTS，都建在一棵树里，这棵树更新Q-Value。

        states.append(state.board)
        policies.append(policy)
        values.append(value)
        actions.append(action[0]*board_size + action[1])

        state.move(action)  # 执行下棋 take action

    # 计算真实的rewards
    final_reward = state.get_reward()

    target_values = torch.tensor(
        [final_reward * ((-1) ** i) for i in range(len(values))])
    # print(target_values.shape)

    # 训练网络
    optimizer.zero_grad()

    # Policy loss with CrossEntropy
    # pred  = [action x policys]
    # label = [action]
    pred = torch.cat(policies, dim=0)
    label = torch.tensor(actions)
    loss_fn = nn.CrossEntropyLoss()
    policy_loss = loss_fn(pred, label)
    
    # MSE
    value_loss = torch.mean((torch.cat(values) - target_values.detach()) ** 2)
    loss = policy_loss + value_loss
    print(policy_loss)
    print(value_loss)

    loss.backward()
    optimizer.step()

    if episode % 1 == 0:
        print(f"Episode {episode}, Loss: {loss.item()}")
        # print(loss)
        # print(state.board)  # 查看盘面
        print(final_reward)
    # break

tensor(4.1580, grad_fn=<NllLossBackward0>)

tensor(1.0002, grad_fn=<MeanBackward0>)

Episode 0, Loss: 5.158205509185791

1

tensor(4.1580, grad_fn=<NllLossBackward0>)

tensor(1.1256, grad_fn=<MeanBackward0>)

Episode 1, Loss: 5.283540725708008

1

tensor(4.1587, grad_fn=<NllLossBackward0>)

tensor(1.0032, grad_fn=<MeanBackward0>)

Episode 2, Loss: 5.161891937255859

1

tensor(4.1584, grad_fn=<NllLossBackward0>)

tensor(1.0153, grad_fn=<MeanBackward0>)

Episode 3, Loss: 5.173693656921387

1

tensor(4.1588, grad_fn=<NllLossBackward0>)

tensor(1.0175, grad_fn=<MeanBackward0>)

Episode 4, Loss: 5.17629861831665

-1

tensor(4.1582, grad_fn=<NllLossBackward0>)

tensor(1.0037, grad_fn=<MeanBackward0>)

Episode 5, Loss: 5.161882400512695

1

tensor(4.1583, grad_fn=<NllLossBackward0>)

tensor(1.0019, grad_fn=<MeanBackward0>)

Episode 6, Loss: 5.160212516784668

1

tensor(4.1583, grad_fn=<NllLossBackward0>)

tensor(1.0002, grad_fn=<MeanBackward0>)

Episode 7, Loss: 5.158506393432617

1

tensor(4.1585, grad_fn=<NllLossBackward0>)

tensor(1.0015, grad_fn=<MeanBackward0>)

Episode 8, Loss: 5.159980297088623

-1

tensor(4.1580, grad_fn=<NllLossBackward0>)

tensor(1.0014, grad_fn=<MeanBackward0>)

Episode 9, Loss: 5.159428596496582

-1

tensor(4.1584, grad_fn=<NllLossBackward0>)

tensor(0.9997, grad_fn=<MeanBackward0>)

Episode 10, Loss: 5.1581315994262695

1

tensor(4.1580, grad_fn=<NllLossBackward0>)

tensor(1.0010, grad_fn=<MeanBackward0>)

Episode 11, Loss: 5.15908670425415

-1

tensor(4.1579, grad_fn=<NllLossBackward0>)

tensor(1.0010, grad_fn=<MeanBackward0>)

Episode 12, Loss: 5.158845901489258

-1

tensor(4.1585, grad_fn=<NllLossBackward0>)

tensor(0.9999, grad_fn=<MeanBackward0>)

Episode 13, Loss: 5.158390998840332

1

tensor(4.1584, grad_fn=<NllLossBackward0>)

tensor(0.9997, grad_fn=<MeanBackward0>)

Episode 14, Loss: 5.158127307891846

1

tensor(4.1587, grad_fn=<NllLossBackward0>)

tensor(0.9999, grad_fn=<MeanBackward0>)

Episode 15, Loss: 5.158552169799805

1

tensor(4.1578, grad_fn=<NllLossBackward0>)

tensor(1.0004, grad_fn=<MeanBackward0>)

Episode 16, Loss: 5.1581645011901855

-1

tensor(4.1583, grad_fn=<NllLossBackward0>)

tensor(0.9999, grad_fn=<MeanBackward0>)

Episode 17, Loss: 5.158205032348633

1

tensor(4.1585, grad_fn=<NllLossBackward0>)

tensor(1.0002, grad_fn=<MeanBackward0>)

Episode 18, Loss: 5.158718585968018

-1

tensor(4.1582, grad_fn=<NllLossBackward0>)

tensor(0.9999, grad_fn=<MeanBackward0>)

Episode 19, Loss: 5.158193111419678

1

tensor(4.1583, grad_fn=<NllLossBackward0>)

tensor(0.9999, grad_fn=<MeanBackward0>)

Episode 20, Loss: 5.1581597328186035

1

tensor(4.1584, grad_fn=<NllLossBackward0>)

tensor(0.9998, grad_fn=<MeanBackward0>)

Episode 21, Loss: 5.158197402954102

1

tensor(4.1587, grad_fn=<NllLossBackward0>)

tensor(0.9999, grad_fn=<MeanBackward0>)

Episode 22, Loss: 5.158637523651123

1

tensor(4.1577, grad_fn=<NllLossBackward0>)

tensor(1.0004, grad_fn=<MeanBackward0>)

Episode 23, Loss: 5.158060073852539

-1

tensor(4.1585, grad_fn=<NllLossBackward0>)

tensor(0.9998, grad_fn=<MeanBackward0>)

Episode 24, Loss: 5.158313274383545

1

tensor(4.1585, grad_fn=<NllLossBackward0>)

tensor(1.0003, grad_fn=<MeanBackward0>)

Episode 25, Loss: 5.158778190612793

-1

tensor(4.1585, grad_fn=<NllLossBackward0>)

tensor(1.0002, grad_fn=<MeanBackward0>)

Episode 26, Loss: 5.158674716949463

-1

tensor(4.1585, grad_fn=<NllLossBackward0>)

tensor(1.0002, grad_fn=<MeanBackward0>)

Episode 27, Loss: 5.158652305603027

-1

tensor(4.1582, grad_fn=<NllLossBackward0>)

tensor(0.9998, grad_fn=<MeanBackward0>)

Episode 28, Loss: 5.157996654510498

1

tensor(4.1582, grad_fn=<NllLossBackward0>)

tensor(0.9996, grad_fn=<MeanBackward0>)

Episode 29, Loss: 5.157797336578369

1

tensor(4.1574, grad_fn=<NllLossBackward0>)

tensor(1.0002, grad_fn=<MeanBackward0>)

Episode 30, Loss: 5.157620429992676

-1

tensor(4.1574, grad_fn=<NllLossBackward0>)

tensor(1.0002, grad_fn=<MeanBackward0>)

Episode 31, Loss: 5.1575727462768555

-1

tensor(4.1584, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 32, Loss: 5.1585259437561035

-1

tensor(4.1583, grad_fn=<NllLossBackward0>)

tensor(0.9997, grad_fn=<MeanBackward0>)

Episode 33, Loss: 5.157955169677734

1

tensor(4.1581, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 34, Loss: 5.158199310302734

-1

tensor(4.1573, grad_fn=<NllLossBackward0>)

tensor(0.9991, grad_fn=<MeanBackward0>)

Episode 35, Loss: 5.156397819519043

1

tensor(4.1573, grad_fn=<NllLossBackward0>)

tensor(0.9991, grad_fn=<MeanBackward0>)

Episode 36, Loss: 5.156373023986816

1

tensor(4.1582, grad_fn=<NllLossBackward0>)

tensor(0.9997, grad_fn=<MeanBackward0>)

Episode 37, Loss: 5.157869338989258

1

tensor(4.1577, grad_fn=<NllLossBackward0>)

tensor(1.0002, grad_fn=<MeanBackward0>)

Episode 38, Loss: 5.157896041870117

-1

tensor(4.1576, grad_fn=<NllLossBackward0>)

tensor(1.0002, grad_fn=<MeanBackward0>)

Episode 39, Loss: 5.1578779220581055

-1

tensor(4.1580, grad_fn=<NllLossBackward0>)

tensor(0.9996, grad_fn=<MeanBackward0>)

Episode 40, Loss: 5.157678604125977

1

tensor(4.1575, grad_fn=<NllLossBackward0>)

tensor(1.0004, grad_fn=<MeanBackward0>)

Episode 41, Loss: 5.157853603363037

-1

tensor(4.1580, grad_fn=<NllLossBackward0>)

tensor(1.0002, grad_fn=<MeanBackward0>)

Episode 42, Loss: 5.158178806304932

-1

tensor(4.1579, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 43, Loss: 5.158017635345459

-1

tensor(4.1589, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 44, Loss: 5.158977031707764

-1

tensor(4.1581, grad_fn=<NllLossBackward0>)

tensor(0.9999, grad_fn=<MeanBackward0>)

Episode 45, Loss: 5.15790319442749

1

tensor(4.1579, grad_fn=<NllLossBackward0>)

tensor(1.0000, grad_fn=<MeanBackward0>)

Episode 46, Loss: 5.157894611358643

-1

tensor(4.1574, grad_fn=<NllLossBackward0>)

tensor(0.9998, grad_fn=<MeanBackward0>)

Episode 47, Loss: 5.157194137573242

1

tensor(4.1574, grad_fn=<NllLossBackward0>)

tensor(0.9998, grad_fn=<MeanBackward0>)

Episode 48, Loss: 5.157135486602783

1

tensor(4.1573, grad_fn=<NllLossBackward0>)

tensor(0.9998, grad_fn=<MeanBackward0>)

Episode 49, Loss: 5.157099723815918

1

tensor(4.1588, grad_fn=<NllLossBackward0>)

tensor(1.0000, grad_fn=<MeanBackward0>)

Episode 50, Loss: 5.1588134765625

-1

tensor(4.1583, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 51, Loss: 5.158371925354004

-1

tensor(4.1586, grad_fn=<NllLossBackward0>)

tensor(0.9999, grad_fn=<MeanBackward0>)

Episode 52, Loss: 5.158471584320068

1

tensor(4.1582, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 53, Loss: 5.1582512855529785

-1

tensor(4.1583, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 54, Loss: 5.1583781242370605

-1

tensor(4.1583, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 55, Loss: 5.158363342285156

-1

tensor(4.1586, grad_fn=<NllLossBackward0>)

tensor(0.9998, grad_fn=<MeanBackward0>)

Episode 56, Loss: 5.158326625823975

1

tensor(4.1584, grad_fn=<NllLossBackward0>)

tensor(1.0002, grad_fn=<MeanBackward0>)

Episode 57, Loss: 5.158545017242432

-1

tensor(4.1584, grad_fn=<NllLossBackward0>)

tensor(0.9997, grad_fn=<MeanBackward0>)

Episode 58, Loss: 5.15818452835083

1

tensor(4.1584, grad_fn=<NllLossBackward0>)

tensor(0.9997, grad_fn=<MeanBackward0>)

Episode 59, Loss: 5.1581926345825195

1

tensor(4.1579, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 60, Loss: 5.15797758102417

-1

tensor(4.1567, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 61, Loss: 5.156763076782227

-1

tensor(4.1581, grad_fn=<NllLossBackward0>)

tensor(1.0003, grad_fn=<MeanBackward0>)

Episode 62, Loss: 5.158412933349609

-1

tensor(4.1578, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 63, Loss: 5.1578545570373535

-1

tensor(4.1580, grad_fn=<NllLossBackward0>)

tensor(1.0000, grad_fn=<MeanBackward0>)

Episode 64, Loss: 5.158049583435059

-1

tensor(4.1577, grad_fn=<NllLossBackward0>)

tensor(1.0000, grad_fn=<MeanBackward0>)

Episode 65, Loss: 5.157764434814453

-1

tensor(4.1575, grad_fn=<NllLossBackward0>)

tensor(1.0002, grad_fn=<MeanBackward0>)

Episode 66, Loss: 5.157733917236328

-1

tensor(4.1575, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 67, Loss: 5.157605171203613

-1

tensor(4.1578, grad_fn=<NllLossBackward0>)

tensor(1.0005, grad_fn=<MeanBackward0>)

Episode 68, Loss: 5.1582932472229

1

tensor(4.1575, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 69, Loss: 5.157556056976318

-1

tensor(4.1566, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 70, Loss: 5.156741142272949

-1

tensor(4.1564, grad_fn=<NllLossBackward0>)

tensor(1.0000, grad_fn=<MeanBackward0>)

Episode 71, Loss: 5.1563920974731445

-1

tensor(4.1563, grad_fn=<NllLossBackward0>)

tensor(1.0000, grad_fn=<MeanBackward0>)

Episode 72, Loss: 5.156369209289551

-1

tensor(4.1577, grad_fn=<NllLossBackward0>)

tensor(1.0002, grad_fn=<MeanBackward0>)

Episode 73, Loss: 5.157832145690918

1

tensor(4.1575, grad_fn=<NllLossBackward0>)

tensor(1.0003, grad_fn=<MeanBackward0>)

Episode 74, Loss: 5.157852649688721

1

tensor(4.1578, grad_fn=<NllLossBackward0>)

tensor(0.9998, grad_fn=<MeanBackward0>)

Episode 75, Loss: 5.157651424407959

1

tensor(4.1580, grad_fn=<NllLossBackward0>)

tensor(0.9997, grad_fn=<MeanBackward0>)

Episode 76, Loss: 5.157706260681152

1

tensor(4.1579, grad_fn=<NllLossBackward0>)

tensor(1.0002, grad_fn=<MeanBackward0>)

Episode 77, Loss: 5.158102989196777

-1

tensor(4.1588, grad_fn=<NllLossBackward0>)

tensor(1.0002, grad_fn=<MeanBackward0>)

Episode 78, Loss: 5.159038543701172

-1

tensor(4.1579, grad_fn=<NllLossBackward0>)

tensor(1.0003, grad_fn=<MeanBackward0>)

Episode 79, Loss: 5.158234596252441

-1

tensor(4.1580, grad_fn=<NllLossBackward0>)

tensor(0.9997, grad_fn=<MeanBackward0>)

Episode 80, Loss: 5.157654762268066

1

tensor(4.1585, grad_fn=<NllLossBackward0>)

tensor(1.0004, grad_fn=<MeanBackward0>)

Episode 81, Loss: 5.15886116027832

-1

tensor(4.1578, grad_fn=<NllLossBackward0>)

tensor(0.9996, grad_fn=<MeanBackward0>)

Episode 82, Loss: 5.157451152801514

1

tensor(4.1565, grad_fn=<NllLossBackward0>)

tensor(1.0004, grad_fn=<MeanBackward0>)

Episode 83, Loss: 5.156889915466309

-1

tensor(4.1586, grad_fn=<NllLossBackward0>)

tensor(0.9998, grad_fn=<MeanBackward0>)

Episode 84, Loss: 5.158379077911377

1

tensor(4.1579, grad_fn=<NllLossBackward0>)

tensor(0.9998, grad_fn=<MeanBackward0>)

Episode 85, Loss: 5.157666206359863

1

tensor(4.1561, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 86, Loss: 5.156154155731201

-1

tensor(4.1560, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 87, Loss: 5.1560845375061035

-1

tensor(4.1577, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 88, Loss: 5.157866477966309

-1

tensor(4.1559, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 89, Loss: 5.155933856964111

-1

tensor(4.1570, grad_fn=<NllLossBackward0>)

tensor(0.9999, grad_fn=<MeanBackward0>)

Episode 90, Loss: 5.156959056854248

1

tensor(4.1570, grad_fn=<NllLossBackward0>)

tensor(1.0000, grad_fn=<MeanBackward0>)

Episode 91, Loss: 5.156965732574463

1

tensor(4.1575, grad_fn=<NllLossBackward0>)

tensor(0.9998, grad_fn=<MeanBackward0>)

Episode 92, Loss: 5.157318115234375

1

tensor(4.1578, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 93, Loss: 5.157894134521484

-1

tensor(4.1554, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 94, Loss: 5.155502796173096

1

tensor(4.1582, grad_fn=<NllLossBackward0>)

tensor(1.0000, grad_fn=<MeanBackward0>)

Episode 95, Loss: 5.1582183837890625

-1

tensor(4.1574, grad_fn=<NllLossBackward0>)

tensor(1.0004, grad_fn=<MeanBackward0>)

Episode 96, Loss: 5.15783166885376

1

tensor(4.1576, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 97, Loss: 5.15770959854126

1

tensor(4.1570, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 98, Loss: 5.157075881958008

-1

tensor(4.1566, grad_fn=<NllLossBackward0>)

tensor(0.9996, grad_fn=<MeanBackward0>)

Episode 99, Loss: 5.156263828277588

1

tensor(4.1567, grad_fn=<NllLossBackward0>)

tensor(1.0010, grad_fn=<MeanBackward0>)

Episode 100, Loss: 5.157687664031982

-1

tensor(4.1565, grad_fn=<NllLossBackward0>)

tensor(0.9995, grad_fn=<MeanBackward0>)

Episode 101, Loss: 5.155990123748779

1

tensor(4.1578, grad_fn=<NllLossBackward0>)

tensor(0.9999, grad_fn=<MeanBackward0>)

Episode 102, Loss: 5.157690048217773

1

tensor(4.1572, grad_fn=<NllLossBackward0>)

tensor(1.0010, grad_fn=<MeanBackward0>)

Episode 103, Loss: 5.1582207679748535

-1

tensor(4.1580, grad_fn=<NllLossBackward0>)

tensor(1.0002, grad_fn=<MeanBackward0>)

Episode 104, Loss: 5.158232688903809

-1

tensor(4.1573, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 105, Loss: 5.157431602478027

-1

tensor(4.1547, grad_fn=<NllLossBackward0>)

tensor(1.0000, grad_fn=<MeanBackward0>)

Episode 106, Loss: 5.154730319976807

-1

tensor(4.1573, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 107, Loss: 5.157392978668213

1

tensor(4.1564, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 108, Loss: 5.156487941741943

-1

tensor(4.1572, grad_fn=<NllLossBackward0>)

tensor(1.0006, grad_fn=<MeanBackward0>)

Episode 109, Loss: 5.157773494720459

1

tensor(4.1558, grad_fn=<NllLossBackward0>)

tensor(1.0002, grad_fn=<MeanBackward0>)

Episode 110, Loss: 5.1559247970581055

-1

tensor(4.1557, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 111, Loss: 5.155786514282227

-1

tensor(4.1562, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 112, Loss: 5.156264305114746

-1

tensor(4.1556, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 113, Loss: 5.155662536621094

-1

tensor(4.1576, grad_fn=<NllLossBackward0>)

tensor(0.9999, grad_fn=<MeanBackward0>)

Episode 114, Loss: 5.157523155212402

1

tensor(4.1556, grad_fn=<NllLossBackward0>)

tensor(1.0004, grad_fn=<MeanBackward0>)

Episode 115, Loss: 5.155941009521484

1

tensor(4.1571, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 116, Loss: 5.157131671905518

-1

tensor(4.1571, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 117, Loss: 5.157192707061768

-1

tensor(4.1567, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 118, Loss: 5.156780242919922

-1

tensor(4.1571, grad_fn=<NllLossBackward0>)

tensor(0.9997, grad_fn=<MeanBackward0>)

Episode 119, Loss: 5.156826019287109

1

tensor(4.1566, grad_fn=<NllLossBackward0>)

tensor(0.9996, grad_fn=<MeanBackward0>)

Episode 120, Loss: 5.156254291534424

1

tensor(4.1565, grad_fn=<NllLossBackward0>)

tensor(0.9998, grad_fn=<MeanBackward0>)

Episode 121, Loss: 5.156269550323486

1

tensor(4.1565, grad_fn=<NllLossBackward0>)

tensor(0.9997, grad_fn=<MeanBackward0>)

Episode 122, Loss: 5.156192302703857

1

tensor(4.1520, grad_fn=<NllLossBackward0>)

tensor(0.9994, grad_fn=<MeanBackward0>)

Episode 123, Loss: 5.15139102935791

1

tensor(4.1568, grad_fn=<NllLossBackward0>)

tensor(0.9997, grad_fn=<MeanBackward0>)

Episode 124, Loss: 5.156571388244629

1

tensor(4.1562, grad_fn=<NllLossBackward0>)

tensor(0.9997, grad_fn=<MeanBackward0>)

Episode 125, Loss: 5.155822277069092

1

tensor(4.1546, grad_fn=<NllLossBackward0>)

tensor(1.0002, grad_fn=<MeanBackward0>)

Episode 126, Loss: 5.154823303222656

-1

tensor(4.1543, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 127, Loss: 5.154346942901611

-1

tensor(4.1560, grad_fn=<NllLossBackward0>)

tensor(1.0000, grad_fn=<MeanBackward0>)

Episode 128, Loss: 5.155978679656982

1

tensor(4.1551, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 129, Loss: 5.155190944671631

-1

tensor(4.1552, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 130, Loss: 5.155210971832275

-1

tensor(4.1572, grad_fn=<NllLossBackward0>)

tensor(1.0000, grad_fn=<MeanBackward0>)

Episode 131, Loss: 5.157182693481445

-1

tensor(4.1562, grad_fn=<NllLossBackward0>)

tensor(1.0000, grad_fn=<MeanBackward0>)

Episode 132, Loss: 5.156215190887451

-1

tensor(4.1552, grad_fn=<NllLossBackward0>)

tensor(1.0007, grad_fn=<MeanBackward0>)

Episode 133, Loss: 5.155872344970703

1

tensor(4.1489, grad_fn=<NllLossBackward0>)

tensor(0.9999, grad_fn=<MeanBackward0>)

Episode 134, Loss: 5.148799419403076

1

tensor(4.1553, grad_fn=<NllLossBackward0>)

tensor(1.0005, grad_fn=<MeanBackward0>)

Episode 135, Loss: 5.155738353729248

-1

tensor(4.1522, grad_fn=<NllLossBackward0>)

tensor(0.9993, grad_fn=<MeanBackward0>)

Episode 136, Loss: 5.1515212059021

1

tensor(4.1473, grad_fn=<NllLossBackward0>)

tensor(0.9979, grad_fn=<MeanBackward0>)

Episode 137, Loss: 5.145259380340576

1

tensor(4.1530, grad_fn=<NllLossBackward0>)

tensor(1.0032, grad_fn=<MeanBackward0>)

Episode 138, Loss: 5.156164169311523

-1

tensor(4.1526, grad_fn=<NllLossBackward0>)

tensor(1.0023, grad_fn=<MeanBackward0>)

Episode 139, Loss: 5.15496826171875

-1

tensor(4.1561, grad_fn=<NllLossBackward0>)

tensor(0.9997, grad_fn=<MeanBackward0>)

Episode 140, Loss: 5.1558051109313965

1

tensor(4.1564, grad_fn=<NllLossBackward0>)

tensor(0.9997, grad_fn=<MeanBackward0>)

Episode 141, Loss: 5.156032562255859

1

tensor(4.1580, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 142, Loss: 5.1581292152404785

1

tensor(4.1494, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 143, Loss: 5.149531841278076

-1

tensor(4.1523, grad_fn=<NllLossBackward0>)

tensor(1.0012, grad_fn=<MeanBackward0>)

Episode 144, Loss: 5.153533458709717

1

tensor(4.1516, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 145, Loss: 5.1517229080200195

-1

tensor(4.1541, grad_fn=<NllLossBackward0>)

tensor(1.0000, grad_fn=<MeanBackward0>)

Episode 146, Loss: 5.15408182144165

-1

tensor(4.1357, grad_fn=<NllLossBackward0>)

tensor(0.9990, grad_fn=<MeanBackward0>)

Episode 147, Loss: 5.1346635818481445

1

tensor(4.1344, grad_fn=<NllLossBackward0>)

tensor(0.9973, grad_fn=<MeanBackward0>)

Episode 148, Loss: 5.131606578826904

1

tensor(4.1525, grad_fn=<NllLossBackward0>)

tensor(1.0022, grad_fn=<MeanBackward0>)

Episode 149, Loss: 5.15472412109375

-1

tensor(4.1394, grad_fn=<NllLossBackward0>)

tensor(1.0034, grad_fn=<MeanBackward0>)

Episode 150, Loss: 5.142827033996582

-1

tensor(4.1572, grad_fn=<NllLossBackward0>)

tensor(1.0020, grad_fn=<MeanBackward0>)

Episode 151, Loss: 5.159233093261719

-1

tensor(4.1555, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 152, Loss: 5.155611991882324

1

tensor(4.1484, grad_fn=<NllLossBackward0>)

tensor(1.0006, grad_fn=<MeanBackward0>)

Episode 153, Loss: 5.148964881896973

-1

tensor(4.1479, grad_fn=<NllLossBackward0>)

tensor(1.0006, grad_fn=<MeanBackward0>)

Episode 154, Loss: 5.148451805114746

-1

tensor(4.1551, grad_fn=<NllLossBackward0>)

tensor(1.0016, grad_fn=<MeanBackward0>)

Episode 155, Loss: 5.156682968139648

-1

tensor(4.1547, grad_fn=<NllLossBackward0>)

tensor(1.0010, grad_fn=<MeanBackward0>)

Episode 156, Loss: 5.155727863311768

-1

tensor(4.1414, grad_fn=<NllLossBackward0>)

tensor(0.9997, grad_fn=<MeanBackward0>)

Episode 157, Loss: 5.141110420227051

1

tensor(4.1408, grad_fn=<NllLossBackward0>)

tensor(0.9992, grad_fn=<MeanBackward0>)

Episode 158, Loss: 5.139965057373047

1

tensor(4.1402, grad_fn=<NllLossBackward0>)

tensor(0.9991, grad_fn=<MeanBackward0>)

Episode 159, Loss: 5.1392998695373535

1

tensor(4.1553, grad_fn=<NllLossBackward0>)

tensor(1.0003, grad_fn=<MeanBackward0>)

Episode 160, Loss: 5.155609130859375

1

tensor(4.1519, grad_fn=<NllLossBackward0>)

tensor(1.0003, grad_fn=<MeanBackward0>)

Episode 161, Loss: 5.152169227600098

1

tensor(4.1514, grad_fn=<NllLossBackward0>)

tensor(1.0002, grad_fn=<MeanBackward0>)

Episode 162, Loss: 5.151551723480225

1

tensor(4.1471, grad_fn=<NllLossBackward0>)

tensor(0.9998, grad_fn=<MeanBackward0>)

Episode 163, Loss: 5.146843433380127

1

tensor(4.1424, grad_fn=<NllLossBackward0>)

tensor(0.9995, grad_fn=<MeanBackward0>)

Episode 164, Loss: 5.141849040985107

1

tensor(4.1497, grad_fn=<NllLossBackward0>)

tensor(0.9997, grad_fn=<MeanBackward0>)

Episode 165, Loss: 5.149496078491211

1

tensor(4.1491, grad_fn=<NllLossBackward0>)

tensor(0.9998, grad_fn=<MeanBackward0>)

Episode 166, Loss: 5.148893356323242

1

tensor(4.1484, grad_fn=<NllLossBackward0>)

tensor(0.9999, grad_fn=<MeanBackward0>)

Episode 167, Loss: 5.148308753967285

1

tensor(4.1324, grad_fn=<NllLossBackward0>)

tensor(1.0000, grad_fn=<MeanBackward0>)

Episode 168, Loss: 5.13240909576416

1

tensor(4.1389, grad_fn=<NllLossBackward0>)

tensor(0.9997, grad_fn=<MeanBackward0>)

Episode 169, Loss: 5.138634204864502

1

tensor(4.1378, grad_fn=<NllLossBackward0>)

tensor(0.9995, grad_fn=<MeanBackward0>)

Episode 170, Loss: 5.137369632720947

1

tensor(4.1374, grad_fn=<NllLossBackward0>)

tensor(0.9994, grad_fn=<MeanBackward0>)

Episode 171, Loss: 5.1367926597595215

1

tensor(4.1446, grad_fn=<NllLossBackward0>)

tensor(0.9999, grad_fn=<MeanBackward0>)

Episode 172, Loss: 5.144509315490723

1

tensor(4.1451, grad_fn=<NllLossBackward0>)

tensor(1.0000, grad_fn=<MeanBackward0>)

Episode 173, Loss: 5.145158290863037

1

tensor(4.1278, grad_fn=<NllLossBackward0>)

tensor(0.9991, grad_fn=<MeanBackward0>)

Episode 174, Loss: 5.126962184906006

1

tensor(4.1354, grad_fn=<NllLossBackward0>)

tensor(1.0013, grad_fn=<MeanBackward0>)

Episode 175, Loss: 5.1366868019104

-1

tensor(4.1377, grad_fn=<NllLossBackward0>)

tensor(1.0007, grad_fn=<MeanBackward0>)

Episode 176, Loss: 5.138416290283203

-1

tensor(4.1429, grad_fn=<NllLossBackward0>)

tensor(0.9997, grad_fn=<MeanBackward0>)

Episode 177, Loss: 5.14254903793335

1

tensor(4.1416, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 178, Loss: 5.141651153564453

-1

tensor(4.1320, grad_fn=<NllLossBackward0>)

tensor(1.0000, grad_fn=<MeanBackward0>)

Episode 179, Loss: 5.13205623626709

-1

tensor(4.1362, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 180, Loss: 5.136329174041748

-1

tensor(4.1196, grad_fn=<NllLossBackward0>)

tensor(1.0003, grad_fn=<MeanBackward0>)

Episode 181, Loss: 5.1198883056640625

-1

tensor(4.1186, grad_fn=<NllLossBackward0>)

tensor(1.0004, grad_fn=<MeanBackward0>)

Episode 182, Loss: 5.119052410125732

-1

tensor(4.1345, grad_fn=<NllLossBackward0>)

tensor(1.0014, grad_fn=<MeanBackward0>)

Episode 183, Loss: 5.135869979858398

1

tensor(4.1333, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 184, Loss: 5.133411884307861

-1

tensor(4.1356, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 185, Loss: 5.135622978210449

-1

tensor(4.1401, grad_fn=<NllLossBackward0>)

tensor(1.0000, grad_fn=<MeanBackward0>)

Episode 186, Loss: 5.140145778656006

1

tensor(4.1091, grad_fn=<NllLossBackward0>)

tensor(0.9993, grad_fn=<MeanBackward0>)

Episode 187, Loss: 5.108484745025635

1

tensor(4.1337, grad_fn=<NllLossBackward0>)

tensor(0.9997, grad_fn=<MeanBackward0>)

Episode 188, Loss: 5.13338041305542

1

tensor(4.1342, grad_fn=<NllLossBackward0>)

tensor(0.9998, grad_fn=<MeanBackward0>)

Episode 189, Loss: 5.134064197540283

1

tensor(4.1377, grad_fn=<NllLossBackward0>)

tensor(1.0010, grad_fn=<MeanBackward0>)

Episode 190, Loss: 5.138615608215332

-1

tensor(4.1144, grad_fn=<NllLossBackward0>)

tensor(1.0014, grad_fn=<MeanBackward0>)

Episode 191, Loss: 5.115744113922119

-1

tensor(4.1318, grad_fn=<NllLossBackward0>)

tensor(1.0007, grad_fn=<MeanBackward0>)

Episode 192, Loss: 5.132564067840576

1

tensor(4.1381, grad_fn=<NllLossBackward0>)

tensor(1.0005, grad_fn=<MeanBackward0>)

Episode 193, Loss: 5.138628959655762

-1

tensor(4.1323, grad_fn=<NllLossBackward0>)

tensor(1.0004, grad_fn=<MeanBackward0>)

Episode 194, Loss: 5.132693290710449

-1

tensor(4.1337, grad_fn=<NllLossBackward0>)

tensor(0.9998, grad_fn=<MeanBackward0>)

Episode 195, Loss: 5.133512020111084

1

tensor(4.1352, grad_fn=<NllLossBackward0>)

tensor(0.9997, grad_fn=<MeanBackward0>)

Episode 196, Loss: 5.134875297546387

1

tensor(4.1273, grad_fn=<NllLossBackward0>)

tensor(1.0002, grad_fn=<MeanBackward0>)

Episode 197, Loss: 5.127520561218262

-1

tensor(4.1292, grad_fn=<NllLossBackward0>)

tensor(1.0002, grad_fn=<MeanBackward0>)

Episode 198, Loss: 5.129360675811768

-1

tensor(4.1149, grad_fn=<NllLossBackward0>)

tensor(1.0001, grad_fn=<MeanBackward0>)

Episode 199, Loss: 5.114990234375

-1

## MCTS Inference

In [11]:
state = GomokuState(board_size=board_size, gomoku_number=gomoku_number)
while not state.is_terminal():
    action = mcts_move(state, net, 100)
    state.move(action)
    print(state.board)
print(state.get_reward())
print("Game over")

tensor([[[[0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 1., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0.]]]])

tensor([[[[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [-1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [-1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0., -1.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [-1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0., -1.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [-1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
          [ 0., -1.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0., -1.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [-1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
          [ 0., -1.,  0.,  0.,  1.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0., -1.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [-1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
          [ 0., -1.,  0.,  0.,  1.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0., -1.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [-1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
          [ 0., -1.,  0.,  0.,  1.,  0.,  0.,  1.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0., -1.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [-1.,  0.,  0.,  1., -1.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
          [ 0., -1.,  0.,  0.,  1.,  0.,  0.,  1.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0., -1.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [-1.,  1.,  0.,  1., -1.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
          [ 0., -1.,  0.,  0.,  1.,  0.,  0.,  1.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0., -1.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [-1.,  1.,  0.,  1., -1.,  0.,  0.,  0.],
          [ 0.,  0., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 0., -1.,  0.,  0.,  1.,  0.,  0.,  1.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0., -1.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0.,  0.],
          [ 0.,  0., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 0., -1.,  0.,  0.,  1.,  0.,  0.,  1.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0., -1.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0.,  0.],
          [ 0.,  0., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 0., -1.,  0.,  0.,  1.,  0.,  0.,  1.],
          [ 0.,  0.,  0.,  0.,  0.,  0., -1.,  0.],
          [ 0.,  0., -1.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0.,  0.],
          [ 0.,  0., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 0., -1.,  0.,  0.,  1.,  0.,  0.,  1.],
          [ 0.,  0.,  1.,  0.,  0.,  0., -1.,  0.],
          [ 0.,  0., -1.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0.,  0.],
          [ 0.,  0., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 0., -1.,  0.,  0.,  1.,  0.,  0.,  1.],
          [ 0.,  0.,  1.,  0.,  0.,  0., -1.,  0.],
          [ 0., -1., -1.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0.,  0.],
          [ 0.,  0., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 0., -1.,  0.,  0.,  1.,  0.,  0.,  1.],
          [ 0.,  0.,  1.,  0.,  0.,  0., -1.,  0.],
          [ 0., -1., -1.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 1.,  0.,  0.,  0., -1.,  0.,  0.,  0.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0.,  0.],
          [ 0.,  0., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 0., -1.,  0.,  0.,  1.,  0.,  0.,  1.],
          [ 0.,  0.,  1.,  0.,  0.,  0., -1.,  0.],
          [ 0., -1., -1.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 1.,  0.,  0.,  0., -1.,  0.,  0.,  0.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0.,  0.],
          [ 0.,  0., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 0., -1.,  0.,  0.,  1.,  0.,  0.,  1.],
          [ 0.,  0.,  1.,  0.,  0.,  0., -1.,  1.],
          [ 0., -1., -1.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 1.,  0.,  0.,  0., -1.,  0.,  0.,  0.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0.,  0.],
          [ 0.,  0., -1., -1.,  0.,  0.,  1.,  0.],
          [ 0., -1.,  0.,  0.,  1.,  0.,  0.,  1.],
          [ 0.,  0.,  1.,  0.,  0.,  0., -1.,  1.],
          [ 0., -1., -1.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.]]]])

tensor([[[[-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 1.,  0.,  0.,  0., -1.,  0.,  0.,  0.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0.,  0.],
          [ 0.,  0., -1., -1.,  0.,  0.,  1.,  0.],
          [ 0., -1.,  0.,  0.,  1.,  0.,  0.,  1.],
          [ 0.,  0.,  1.,  0.,  0.,  0., -1.,  1.],
          [ 0., -1., -1.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.]]]])

tensor([[[[-1.,  0., -1.,  0.,  0.,  0.,  0.,  0.],
          [ 1.,  0.,  0.,  0., -1.,  0.,  0.,  0.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0.,  0.],
          [ 0.,  0., -1., -1.,  0.,  0.,  1.,  0.],
          [ 0., -1.,  0.,  0.,  1.,  0.,  0.,  1.],
          [ 0.,  0.,  1.,  0.,  0.,  0., -1.,  1.],
          [ 0., -1., -1.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.]]]])

tensor([[[[-1.,  0., -1.,  0.,  0.,  0.,  0.,  0.],
          [ 1.,  0.,  0.,  0., -1.,  0.,  0.,  0.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0.,  0.],
          [ 0.,  0., -1., -1.,  0.,  0.,  1.,  0.],
          [ 0., -1.,  0.,  0.,  1.,  0.,  0.,  1.],
          [ 0.,  0.,  1.,  0.,  0.,  0., -1.,  1.],
          [ 1., -1., -1.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.]]]])

tensor([[[[-1.,  0., -1.,  0.,  0.,  0.,  0.,  0.],
          [ 1.,  0.,  0.,  0., -1.,  0.,  0.,  0.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0.,  0.],
          [ 0.,  0., -1., -1.,  0.,  0.,  1.,  0.],
          [ 0., -1.,  0.,  0.,  1.,  0.,  0.,  1.],
          [ 0.,  0.,  1.,  0., -1.,  0., -1.,  1.],
          [ 1., -1., -1.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.]]]])

tensor([[[[-1.,  0., -1.,  0.,  0.,  0.,  0.,  0.],
          [ 1.,  0.,  0.,  0., -1.,  0.,  0.,  0.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0.,  0.],
          [ 0.,  0., -1., -1.,  0.,  0.,  1.,  0.],
          [ 0., -1.,  0.,  0.,  1.,  0.,  0.,  1.],
          [ 0.,  0.,  1.,  0., -1.,  0., -1.,  1.],
          [ 1., -1., -1.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  1.,  0.,  0.,  0.,  0.,  1.,  1.]]]])

tensor([[[[-1.,  0., -1.,  0.,  0.,  0.,  0.,  0.],
          [ 1., -1.,  0.,  0., -1.,  0.,  0.,  0.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0.,  0.],
          [ 0.,  0., -1., -1.,  0.,  0.,  1.,  0.],
          [ 0., -1.,  0.,  0.,  1.,  0.,  0.,  1.],
          [ 0.,  0.,  1.,  0., -1.,  0., -1.,  1.],
          [ 1., -1., -1.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  1.,  0.,  0.,  0.,  0.,  1.,  1.]]]])

tensor([[[[-1.,  0., -1.,  0.,  0.,  0.,  0.,  0.],
          [ 1., -1.,  0.,  0., -1.,  0.,  0.,  0.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0.,  0.],
          [ 0.,  0., -1., -1.,  0.,  0.,  1.,  0.],
          [ 0., -1.,  0.,  0.,  1.,  0.,  0.,  1.],
          [ 0.,  0.,  1.,  0., -1.,  1., -1.,  1.],
          [ 1., -1., -1.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  1.,  0.,  0.,  0.,  0.,  1.,  1.]]]])

tensor([[[[-1.,  0., -1.,  0.,  0.,  0.,  0.,  0.],
          [ 1., -1.,  0.,  0., -1.,  0.,  0.,  0.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0.,  0.],
          [ 0.,  0., -1., -1.,  0.,  0.,  1.,  0.],
          [ 0., -1.,  0.,  0.,  1., -1.,  0.,  1.],
          [ 0.,  0.,  1.,  0., -1.,  1., -1.,  1.],
          [ 1., -1., -1.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  1.,  0.,  0.,  0.,  0.,  1.,  1.]]]])

tensor([[[[-1.,  0., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 1., -1.,  0.,  0., -1.,  0.,  0.,  0.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0.,  0.],
          [ 0.,  0., -1., -1.,  0.,  0.,  1.,  0.],
          [ 0., -1.,  0.,  0.,  1., -1.,  0.,  1.],
          [ 0.,  0.,  1.,  0., -1.,  1., -1.,  1.],
          [ 1., -1., -1.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  1.,  0.,  0.,  0.,  0.,  1.,  1.]]]])

tensor([[[[-1.,  0., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 1., -1.,  0.,  0., -1.,  0.,  0.,  0.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0.,  0.],
          [ 0.,  0., -1., -1.,  0.,  0.,  1.,  0.],
          [ 0., -1.,  0.,  0.,  1., -1.,  0.,  1.],
          [ 0.,  0.,  1.,  0., -1.,  1., -1.,  1.],
          [ 1., -1., -1.,  0.,  0.,  0.,  0., -1.],
          [ 0.,  1.,  0.,  0.,  0.,  0.,  1.,  1.]]]])

tensor([[[[-1.,  0., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 1., -1.,  0.,  0., -1.,  0.,  0.,  0.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0.,  0.],
          [ 0.,  0., -1., -1.,  0.,  0.,  1.,  0.],
          [ 0., -1.,  0.,  0.,  1., -1.,  0.,  1.],
          [ 0.,  0.,  1.,  0., -1.,  1., -1.,  1.],
          [ 1., -1., -1.,  0.,  1.,  0.,  0., -1.],
          [ 0.,  1.,  0.,  0.,  0.,  0.,  1.,  1.]]]])

tensor([[[[-1.,  0., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 1., -1.,  0.,  0., -1.,  0.,  0.,  0.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0.,  0.],
          [ 0.,  0., -1., -1.,  0.,  0.,  1.,  0.],
          [ 0., -1.,  0.,  0.,  1., -1.,  0.,  1.],
          [ 0.,  0.,  1.,  0., -1.,  1., -1.,  1.],
          [ 1., -1., -1.,  0.,  1.,  0.,  0., -1.],
          [ 0.,  1.,  0., -1.,  0.,  0.,  1.,  1.]]]])

tensor([[[[-1.,  0., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 1., -1.,  0.,  0., -1.,  1.,  0.,  0.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0.,  0.],
          [ 0.,  0., -1., -1.,  0.,  0.,  1.,  0.],
          [ 0., -1.,  0.,  0.,  1., -1.,  0.,  1.],
          [ 0.,  0.,  1.,  0., -1.,  1., -1.,  1.],
          [ 1., -1., -1.,  0.,  1.,  0.,  0., -1.],
          [ 0.,  1.,  0., -1.,  0.,  0.,  1.,  1.]]]])

tensor([[[[-1.,  0., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 1., -1.,  0.,  0., -1.,  1.,  0.,  0.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0.,  0.],
          [ 0.,  0., -1., -1.,  0.,  0.,  1.,  0.],
          [ 0., -1.,  0.,  0.,  1., -1.,  0.,  1.],
          [ 0.,  0.,  1., -1., -1.,  1., -1.,  1.],
          [ 1., -1., -1.,  0.,  1.,  0.,  0., -1.],
          [ 0.,  1.,  0., -1.,  0.,  0.,  1.,  1.]]]])

tensor([[[[-1.,  0., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 1., -1.,  0.,  0., -1.,  1.,  0.,  0.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0.,  0.],
          [ 0.,  0., -1., -1.,  0.,  0.,  1.,  0.],
          [ 0., -1.,  0.,  0.,  1., -1.,  0.,  1.],
          [ 0.,  0.,  1., -1., -1.,  1., -1.,  1.],
          [ 1., -1., -1.,  0.,  1.,  1.,  0., -1.],
          [ 0.,  1.,  0., -1.,  0.,  0.,  1.,  1.]]]])

tensor([[[[-1.,  0., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 1., -1.,  0.,  0., -1.,  1.,  0.,  0.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0.,  0.],
          [ 0.,  0., -1., -1.,  0.,  0.,  1.,  0.],
          [ 0., -1.,  0.,  0.,  1., -1.,  0.,  1.],
          [ 0.,  0.,  1., -1., -1.,  1., -1.,  1.],
          [ 1., -1., -1.,  0.,  1.,  1., -1., -1.],
          [ 0.,  1.,  0., -1.,  0.,  0.,  1.,  1.]]]])

tensor([[[[-1.,  0., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 1., -1.,  0.,  0., -1.,  1.,  0.,  0.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0.,  0.],
          [ 0.,  0., -1., -1.,  0.,  0.,  1.,  0.],
          [ 0., -1.,  0.,  0.,  1., -1.,  0.,  1.],
          [ 0.,  0.,  1., -1., -1.,  1., -1.,  1.],
          [ 1., -1., -1.,  0.,  1.,  1., -1., -1.],
          [ 1.,  1.,  0., -1.,  0.,  0.,  1.,  1.]]]])

tensor([[[[-1.,  0., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 1., -1.,  0.,  0., -1.,  1., -1.,  0.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0.,  0.],
          [ 0.,  0., -1., -1.,  0.,  0.,  1.,  0.],
          [ 0., -1.,  0.,  0.,  1., -1.,  0.,  1.],
          [ 0.,  0.,  1., -1., -1.,  1., -1.,  1.],
          [ 1., -1., -1.,  0.,  1.,  1., -1., -1.],
          [ 1.,  1.,  0., -1.,  0.,  0.,  1.,  1.]]]])

tensor([[[[-1.,  0., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 1., -1.,  0.,  0., -1.,  1., -1.,  0.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0.,  0.],
          [ 0.,  0., -1., -1.,  0.,  0.,  1.,  0.],
          [ 0., -1.,  0.,  0.,  1., -1.,  0.,  1.],
          [ 0.,  0.,  1., -1., -1.,  1., -1.,  1.],
          [ 1., -1., -1.,  0.,  1.,  1., -1., -1.],
          [ 1.,  1.,  1., -1.,  0.,  0.,  1.,  1.]]]])

tensor([[[[-1.,  0., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 1., -1.,  0.,  0., -1.,  1., -1.,  0.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0.,  0.],
          [ 0.,  0., -1., -1.,  0.,  0.,  1., -1.],
          [ 0., -1.,  0.,  0.,  1., -1.,  0.,  1.],
          [ 0.,  0.,  1., -1., -1.,  1., -1.,  1.],
          [ 1., -1., -1.,  0.,  1.,  1., -1., -1.],
          [ 1.,  1.,  1., -1.,  0.,  0.,  1.,  1.]]]])

tensor([[[[-1.,  0., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 1., -1.,  0.,  0., -1.,  1., -1.,  1.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0.,  0.],
          [ 0.,  0., -1., -1.,  0.,  0.,  1., -1.],
          [ 0., -1.,  0.,  0.,  1., -1.,  0.,  1.],
          [ 0.,  0.,  1., -1., -1.,  1., -1.,  1.],
          [ 1., -1., -1.,  0.,  1.,  1., -1., -1.],
          [ 1.,  1.,  1., -1.,  0.,  0.,  1.,  1.]]]])

tensor([[[[-1.,  0., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 1., -1., -1.,  0., -1.,  1., -1.,  1.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0.,  0.],
          [ 0.,  0., -1., -1.,  0.,  0.,  1., -1.],
          [ 0., -1.,  0.,  0.,  1., -1.,  0.,  1.],
          [ 0.,  0.,  1., -1., -1.,  1., -1.,  1.],
          [ 1., -1., -1.,  0.,  1.,  1., -1., -1.],
          [ 1.,  1.,  1., -1.,  0.,  0.,  1.,  1.]]]])

tensor([[[[-1.,  0., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 1., -1., -1.,  0., -1.,  1., -1.,  1.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0.,  0.],
          [ 0.,  0., -1., -1.,  0.,  1.,  1., -1.],
          [ 0., -1.,  0.,  0.,  1., -1.,  0.,  1.],
          [ 0.,  0.,  1., -1., -1.,  1., -1.,  1.],
          [ 1., -1., -1.,  0.,  1.,  1., -1., -1.],
          [ 1.,  1.,  1., -1.,  0.,  0.,  1.,  1.]]]])

tensor([[[[-1.,  0., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 1., -1., -1.,  0., -1.,  1., -1.,  1.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0.,  0.],
          [ 0.,  0., -1., -1.,  0.,  1.,  1., -1.],
          [-1., -1.,  0.,  0.,  1., -1.,  0.,  1.],
          [ 0.,  0.,  1., -1., -1.,  1., -1.,  1.],
          [ 1., -1., -1.,  0.,  1.,  1., -1., -1.],
          [ 1.,  1.,  1., -1.,  0.,  0.,  1.,  1.]]]])

tensor([[[[-1.,  0., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 1., -1., -1.,  0., -1.,  1., -1.,  1.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0.,  0.],
          [ 0.,  0., -1., -1.,  0.,  1.,  1., -1.],
          [-1., -1.,  0.,  0.,  1., -1.,  0.,  1.],
          [ 0.,  0.,  1., -1., -1.,  1., -1.,  1.],
          [ 1., -1., -1.,  0.,  1.,  1., -1., -1.],
          [ 1.,  1.,  1., -1.,  1.,  0.,  1.,  1.]]]])

tensor([[[[-1.,  0., -1.,  0.,  0.,  0.,  1.,  0.],
          [ 1., -1., -1.,  0., -1.,  1., -1.,  1.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0., -1.],
          [ 0.,  0., -1., -1.,  0.,  1.,  1., -1.],
          [-1., -1.,  0.,  0.,  1., -1.,  0.,  1.],
          [ 0.,  0.,  1., -1., -1.,  1., -1.,  1.],
          [ 1., -1., -1.,  0.,  1.,  1., -1., -1.],
          [ 1.,  1.,  1., -1.,  1.,  0.,  1.,  1.]]]])

tensor([[[[-1.,  0., -1.,  1.,  0.,  0.,  1.,  0.],
          [ 1., -1., -1.,  0., -1.,  1., -1.,  1.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0., -1.],
          [ 0.,  0., -1., -1.,  0.,  1.,  1., -1.],
          [-1., -1.,  0.,  0.,  1., -1.,  0.,  1.],
          [ 0.,  0.,  1., -1., -1.,  1., -1.,  1.],
          [ 1., -1., -1.,  0.,  1.,  1., -1., -1.],
          [ 1.,  1.,  1., -1.,  1.,  0.,  1.,  1.]]]])

tensor([[[[-1.,  0., -1.,  1.,  0.,  0.,  1.,  0.],
          [ 1., -1., -1.,  0., -1.,  1., -1.,  1.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0., -1.],
          [ 0.,  0., -1., -1.,  0.,  1.,  1., -1.],
          [-1., -1.,  0.,  0.,  1., -1.,  0.,  1.],
          [ 0.,  0.,  1., -1., -1.,  1., -1.,  1.],
          [ 1., -1., -1.,  0.,  1.,  1., -1., -1.],
          [ 1.,  1.,  1., -1.,  1., -1.,  1.,  1.]]]])

tensor([[[[-1.,  0., -1.,  1.,  0.,  1.,  1.,  0.],
          [ 1., -1., -1.,  0., -1.,  1., -1.,  1.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0., -1.],
          [ 0.,  0., -1., -1.,  0.,  1.,  1., -1.],
          [-1., -1.,  0.,  0.,  1., -1.,  0.,  1.],
          [ 0.,  0.,  1., -1., -1.,  1., -1.,  1.],
          [ 1., -1., -1.,  0.,  1.,  1., -1., -1.],
          [ 1.,  1.,  1., -1.,  1., -1.,  1.,  1.]]]])

tensor([[[[-1.,  0., -1.,  1.,  0.,  1.,  1.,  0.],
          [ 1., -1., -1.,  0., -1.,  1., -1.,  1.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0., -1.],
          [ 0.,  0., -1., -1.,  0.,  1.,  1., -1.],
          [-1., -1.,  0.,  0.,  1., -1.,  0.,  1.],
          [ 0.,  0.,  1., -1., -1.,  1., -1.,  1.],
          [ 1., -1., -1., -1.,  1.,  1., -1., -1.],
          [ 1.,  1.,  1., -1.,  1., -1.,  1.,  1.]]]])

tensor([[[[-1.,  0., -1.,  1.,  0.,  1.,  1.,  0.],
          [ 1., -1., -1.,  0., -1.,  1., -1.,  1.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0., -1.],
          [ 0.,  0., -1., -1.,  0.,  1.,  1., -1.],
          [-1., -1.,  0.,  0.,  1., -1.,  0.,  1.],
          [ 0.,  1.,  1., -1., -1.,  1., -1.,  1.],
          [ 1., -1., -1., -1.,  1.,  1., -1., -1.],
          [ 1.,  1.,  1., -1.,  1., -1.,  1.,  1.]]]])

tensor([[[[-1.,  0., -1.,  1.,  0.,  1.,  1.,  0.],
          [ 1., -1., -1.,  0., -1.,  1., -1.,  1.],
          [-1.,  1.,  1.,  1., -1.,  0.,  0., -1.],
          [ 0.,  0., -1., -1.,  0.,  1.,  1., -1.],
          [-1., -1.,  0., -1.,  1., -1.,  0.,  1.],
          [ 0.,  1.,  1., -1., -1.,  1., -1.,  1.],
          [ 1., -1., -1., -1.,  1.,  1., -1., -1.],
          [ 1.,  1.,  1., -1.,  1., -1.,  1.,  1.]]]])

-1

Game over

## MCTS与LLM关系

1. 区别于cartpole，这里的agent在下子时有policy network和value network。
2. 这里要求value估计接近树回溯值
3. 棋子的状态可以看成是连续的(2d棋盘有-1,0,1)，棋子的动作看成是有限的离散集合（动作范围15*15）。
4. LLM的状态是连续的。动作是离散的(词表大小）。这里的问题在于搜索空间更大如llama3为128k
5. LLM与go之间的差异在于，以逐个token来采集，树木深度高，如1024深度，模拟采样的成本过高，且高效采样到terminal成功的难度大，导致有效feedback太少。
6. 如何减少模拟采样的成本，如何有效的采样的正确的推理step，如何得到准确的feedback，是LLM做MCTS-like搜索的关键。
7. 针对6如何来解决？ 

reference：claude-3.5-sonnet